module.exports = {
  "stats-year": "2019-2020",
  teams: {
    avalanche: {
      "franchise-name": "Avalanche",
      "franchise-location": "Colorado",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Philipp Grubauer",
          "player-img": "PhilippGru-removebg-preview.png",
          "team-number": 31,
          position: "Goalie",
          height: "6' 1 \"",
          weight: 191,
          "birth-place": "Rosenheim, Germany",
          shoots: "Left",
          birthday: "1991-11-25",
          "games-played": 174,
          goals: "0",
          assists: "0",
          points: "0 ",
        },
        {
          "player-name": "Cale Makar",
          "player-img": "Avalanche_Makar_Cale.png",
          "team-number": 8,
          position: "Defenseman",
          height: "5' 11\"",
          weight: 187,
          "birth-place": "Calgary, AB, Canada",
          shoots: "Right",
          birthday: "1998-10-30",
          "games-played": 57,
          goals: "12",
          assists: "38",
          points: "50",
        },
        {
          "player-name": "Samuel Girard",
          "player-img": "Girard.png",
          "team-number": 49,
          position: "Defense",
          height: "5' 10 \"",
          weight: 170,
          "birth-place": "Roberval, QC, Canada",
          shoots: "Left",
          birthday: "1998-05-12",
          "games-played": 225,
          goals: "12",
          assists: "72",
          points: "84",
        },
        {
          "player-name": "Gabriel Landeskog",
          "player-img": "Avalanche_Landeskog_92.png",
          "team-number": 92,
          position: "Left Wing",
          height: "6' 1\"",
          weight: 210,
          "birth-place": "Stockholm, Sweden",
          shoots: "Left",
          birthday: "1992-11-23",
          "games-played": 633,
          goals: "198",
          assists: "262",
          points: "460",
        },
        {
          "player-name": "Mikko Rantanen",
          "player-img": "Avalancha-Rantanen-96.png",
          "team-number": 96,
          position: "Right Wing",
          height: "6' 4\"",
          weight: 211,
          "birth-place": "Nousiainen, Finland",
          shoots: "Left",
          birthday: "1996-10-29",
          "games-played": 281,
          goals: "99",
          assists: "151",
          points: "250",
        },
        {
          "player-name": "Nathan MacKinnon",
          "player-img": "Avalanche_MacKinnon_29.png",
          "team-number": 29,
          position: "Center",
          height: "6' 0\"",
          weight: 200,
          "birth-place": "Halifax, NS, Canada",
          shoots: "Right",
          birthday: "1995-09-01",
          "games-played": 525,
          goals: "190",
          assists: "305",
          points: "495",
        },
      ],
    },
    blackhawks: {
      "franchise-name": "Blackhawks",
      "franchise-location": "Chicago",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Malcolm Subban",
          "player-img": "Blackhawks_Malcolm_Subban.png",
          "team-number": 30,
          position: "Goalie",
          height: "6' 2\"",
          weight: 215,
          "birth-place": "Toronto, ON, Canada",
          shoots: "Left",
          birthday: "1993-12-21",
          "games-played": 66,
          goals: "NA",
          assists: "NA",
          points: "NA",
        },
        {
          "player-name": "Brent Seabrook",
          "player-img": "Blackhawks_Seabrook_7.png",
          "team-number": 7,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 220,
          "birth-place": "Richmond, BC, Canada",
          shoots: "Right",
          birthday: "1985-04-20",
          "games-played": 1114,
          goals: "103",
          assists: "361",
          points: "464",
        },
        {
          "player-name": "Duncan Keith",
          "player-img": "Blackhawks_Keith_2.png",
          "team-number": 2,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 192,
          "birth-place": "Winnipeg, MB, Canada",
          shoots: "Left",
          birthday: "1983-07-16",
          "games-played": 1138,
          goals: "101",
          assists: "509",
          points: "610",
        },
        {
          "player-name": "Patrick Kane",
          "player-img": "Blackhawks_Kane_88.png",
          "team-number": 88,
          position: "Right Wing",
          height: "5' 11\"",
          weight: 177,
          "birth-place": "Buffalo, NY, United States",
          shoots: "Left",
          birthday: "1988-11-19",
          "games-played": 973,
          goals: "389",
          assists: "633",
          points: "1022",
        },
        {
          "player-name": "Jonathan Toews",
          "player-img": "Blackhawks_Toews_19.png",
          "team-number": 19,
          position: "Center",
          height: "6' 2\"",
          weight: 201,
          "birth-place": "Winnipeg, MB, Canada",
          shoots: "Left",
          birthday: "1988-04-29",
          "games-played": 943,
          goals: "345",
          assists: "470",
          points: "815",
        },
        {
          "player-name": "Kirby Dach",
          "player-img": "Blackhawks_Kirby_Dach.png",
          "team-number": 77,
          position: "Center",
          height: "6' 4\"",
          weight: 197,
          "birth-place": "Fort Saskatchewan, AB, Canada",
          shoots: "Right",
          birthday: "2001-01-21",
          "games-played": 64,
          goals: "8",
          assists: "15",
          points: "23",
        },
      ],
    },
    bluejackets: {
      "franchise-name": "Blue Jackets",
      "franchise-location": "Columbus",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Seth Jones",
          "player-img": "Jones.png",
          "team-number": 3,
          position: "Defense",
          height: "6' 4\"",
          weight: 220,
          "birth-place": "Arlington, Texas, USA",
          shoots: "Right",
          birthday: "1994-10-03",
          "games-played": 524,
          goals: "60",
          assists: "198",
          points: "258",
        },
        {
          "player-name": "Pierre-Luc Dubois",
          "player-img": "PierreLucDubois.png",
          "team-number": 58,
          position: "Center",
          height: "6' 3\"",
          weight: 207,
          "birth-place": "Ste-Agathe-Des-Monts, QC, CAN",
          shoots: "Left",
          birthday: "1998-06-24",
          "games-played": 234,
          goals: "65",
          assists: "93",
          points: "158",
        },
        {
          "player-name": "Boone Jenner",
          "player-img": "BlueJackets_Jenner_38.png",
          "team-number": 38,
          position: "Center",
          height: "6' 2\"",
          weight: 208,
          "birth-place": "Dorchester, ON, Canada",
          shoots: "Left",
          birthday: "1993-06-15",
          "games-played": 489,
          goals: "113",
          assists: "110",
          points: "223",
        },
        {
          "player-name": "Zach Werenski",
          "player-img": "Werenski.png",
          "team-number": 8,
          position: "Defense",
          height: "6' 2\"",
          weight: 214,
          "birth-place": "Grosse Pointe, MI, United States",
          shoots: "Left",
          birthday: "1997-07-19",
          "games-played": 300,
          goals: "58",
          assists: "111",
          points: "169",
        },
        {
          "player-name": "Cam Atkinson",
          "player-img": "CamAtkinson.png",
          "team-number": 17,
          position: "Right Wing",
          height: "5' 8\"",
          weight: 179,
          "birth-place": "Riverside, CT, USA",
          shoots: "Right",
          birthday: "1989-06-05",
          "games-played": 571,
          goals: "198",
          assists: "170",
          points: "368",
        },
        {
          "player-name": "Gustav Nyquist",
          "player-img": "Blue_Jackets_Nyquist_Gus.png",
          "team-number": 14,
          position: "Center",
          height: "5' 11 \"",
          weight: 179,
          "birth-place": "Halmstad, Sweden",
          shoots: "Left",
          birthday: "1989-09-01",
          "games-played": 570,
          goals: "146",
          assists: "202",
          points: "348",
        },
      ],
    },
    blues: {
      "franchise-name": "Blues",
      "franchise-location": "St. Louis",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Colton Parayko",
          "player-img": "Blues_Parayko_55.png",
          "team-number": 55,
          position: "Defenseman",
          height: "6' 5\"",
          weight: 226,
          "birth-place": "St. Albert, AB, Canada",
          shoots: "Right",
          birthday: "1993-05-12",
          "games-played": 386,
          goals: "39",
          assists: "120",
          points: "159",
        },
        {
          "player-name": "Ryan O'Reilly",
          "player-img": "Blues_OReilly_Ryan.png",
          "team-number": 90,
          position: "Center",
          height: "6' 1\"",
          weight: 216,
          "birth-place": "Clinton, ON, Canada",
          shoots: "Left",
          birthday: "1991-02-07",
          "games-played": 804,
          goals: "195",
          assists: "365",
          points: "560",
        },
        {
          "player-name": "Jaden Schwartz",
          "player-img": "Blues_Schwartz_17.png",
          "team-number": 17,
          position: "Left Wing",
          height: "5' 10\"",
          weight: 190,
          "birth-place": "Wilcox, SK, Canada",
          shoots: "Left",
          birthday: "1992-06-25",
          "games-played": 520,
          goals: "146",
          assists: "218",
          points: "364",
        },
        {
          "player-name": "Torey Krug",
          "player-img": "Blues_Krug_Torey.png",
          "team-number": 47,
          position: "Defenseman",
          height: "5' 9\"",
          weight: 186,
          "birth-place": "Livonia, MI, United States",
          shoots: "Left",
          birthday: "1991-04-12",
          "games-played": 523,
          goals: "67",
          assists: "270",
          points: "337",
        },
        {
          "player-name": "Brayden Schenn",
          "player-img": "Schenn.png",
          "team-number": 10,
          position: "Center",
          height: "6' 1\"",
          weight: 200,
          "birth-place": "Saskatoon, SK, CAN",
          shoots: "Left",
          birthday: "1991-08-22",
          "games-played": 658,
          goals: "179",
          assists: "251",
          points: "430",
        },
        {
          "player-name": "Robert Thomas",
          "player-img": "Blues_Thomas_Robert.png",
          "team-number": 18,
          position: "Center",
          height: "6' 0\"",
          weight: 188,
          "birth-place": "Aurora, ON, Canada",
          shoots: "Right",
          birthday: "1999-07-02",
          "games-played": 136,
          goals: "19",
          assists: "56",
          points: "75",
        },
      ],
    },
    bruins: {
      "franchise-name": "Bruins",
      "franchise-location": "Boston",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Charlie McAvoy",
          "player-img": "Bruins_McAvoy_73.png",
          "team-number": 73,
          position: "Defenseman",
          height: "6' 0\"",
          weight: 208,
          "birth-place": "Long Beach, NY, United States",
          shoots: "Right",
          birthday: "1997-12-21",
          "games-played": 184,
          goals: "19",
          assists: "73",
          points: "92",
        },
        {
          "player-name": "David Krejci",
          "player-img": "Bruins_Krejci_46.png",
          "team-number": 46,
          position: "Center",
          height: "6' 0\"",
          weight: 188,
          "birth-place": "Sternberk, Czech Republic",
          shoots: "Right",
          birthday: "1986-04-28",
          "games-played": 911,
          goals: "207",
          assists: "479",
          points: "686",
        },
        {
          "player-name": "Tuukka Rask",
          "player-img": "Bruins_Rask_40.png",
          "team-number": 40,
          position: "Goalie",
          height: "6' 2\"",
          weight: 185,
          "birth-place": "Savonlinna, Finland",
          shoots: "Left",
          birthday: "1987-03-10",
          "games-played": 70,
          goals: "NA",
          assists: "NA",
          points: "NA",
        },
        {
          "player-name": "Brad Marchand",
          "player-img": "Bruins_Marchand_63.png",
          "team-number": 63,
          position: "Left Wing",
          height: "5' 9\"",
          weight: 183,
          "birth-place": "Halifax, NS, Canada",
          shoots: "Left",
          birthday: "1988-05-11",
          "games-played": 751,
          goals: "290",
          assists: "356",
          points: "646",
        },
        {
          "player-name": "Patrice Bergeron",
          "player-img": "Bruins_Bergeron_37.png",
          "team-number": 37,
          position: "Center",
          height: "6' 2\"",
          weight: 194,
          "birth-place": "Ancienne-Lorette, QC, Canada",
          shoots: "Right",
          birthday: "1985-07-24",
          "games-played": 1089,
          goals: "352",
          assists: "517",
          points: "869",
        },
        {
          "player-name": "David Pastrnak",
          "player-img": "Bruins_Pastrnak_88.png",
          "team-number": 88,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 167,
          "birth-place": "Havirov, Czech Republic",
          shoots: "Right",
          birthday: "1996-05-25",
          "games-played": 390,
          goals: "180",
          assists: "199",
          points: "379",
        },
      ],
    },
    canadiens: {
      "franchise-name": "Canadiens",
      "franchise-location": "Montreal",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "Shea Weber",
          "player-img": "Canadiens_Weber_6.png",
          "team-number": 6,
          position: "Defenseman",
          height: "6' 4\"",
          weight: 236,
          "birth-place": "Sicamous, BC, Canada",
          shoots: "Right",
          birthday: "1985-08-14",
          "games-played": 78,
          goals: "20",
          assists: "31",
          points: "51",
        },
        {
          "player-name": "Jeff Petry",
          "player-img": "Petry.png",
          "team-number": 26,
          position: "Defense",
          height: "6' 3\"",
          weight: 204,
          "birth-place": "Ann Arbor, MI, United States",
          shoots: "Right",
          birthday: "1987-12-09",
          "games-played": 80,
          goals: "8",
          assists: "20",
          points: "28",
        },
        {
          "player-name": "Paul Byron",
          "player-img": "PaulByron.png",
          "team-number": 41,
          position: "Left Wing",
          height: "5' 9 \"",
          weight: 162,
          "birth-place": "Ottawa, ON, Canada",
          shoots: "Left",
          birthday: "1989-04-27",
          "games-played": 82,
          goals: "20",
          assists: "15",
          points: "35 ",
        },
        {
          "player-name": "Brendan Gallagher",
          "player-img": "Canadiens_Gallagher_11.png",
          "team-number": 11,
          position: "Right Wing",
          height: "5' 9\"",
          weight: 182,
          "birth-place": "Edmonton, AB, Canada",
          shoots: "Right",
          birthday: "1992-05-06",
          "games-played": 81,
          goals: "24",
          assists: "23",
          points: "47",
        },
        {
          "player-name": "Jonathan Drouin",
          "player-img": "JonathanDrouin.png",
          "team-number": 92,
          position: "Center",
          height: "6' 0 \"",
          weight: 203,
          "birth-place": "Ste-Agathe, QC, Canada",
          shoots: "Left",
          birthday: "1995-03-28",
          "games-played": 77,
          goals: "13",
          assists: "33",
          points: "46 ",
        },
        {
          "player-name": "Carey Price",
          "player-img": "Canadiens_Price_31.png",
          "team-number": 31,
          position: "Goalie",
          height: "6' 3\"",
          weight: 216,
          "birth-place": "Anahim Lake, BC, Canada",
          shoots: "Left",
          birthday: "1987-08-16",
          "games-played": 66,
          goals: "NA",
          assists: "NA",
          points: "",
        },
      ],
    },
    canucks: {
      "franchise-name": "Canucks",
      "franchise-location": "Vancouver",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "Alex Edler",
          "player-img": "Canucks_Alex_Edler.png",
          "team-number": 23,
          position: "Defenceman",
          height: "6' 3 \"",
          weight: 212,
          "birth-place": "Ostersund, Sweden",
          shoots: "Left",
          birthday: "1986-03-21",
          "games-played": 873,
          goals: "99",
          assists: "302",
          points: "401",
        },
        {
          "player-name": "Bo Horvat",
          "player-img": "Canucks_Horvat_53.png",
          "team-number": 53,
          position: "Center",
          height: "6' 0\"",
          weight: 206,
          "birth-place": "London, ON, Canada",
          shoots: "Left",
          birthday: "1995-05-05",
          "games-played": 446,
          goals: "120",
          assists: "155",
          points: "275",
        },
        {
          "player-name": "Thatcher Demko",
          "player-img": "Canucks_ThatcherDemko.png",
          "team-number": 35,
          position: "Goalie",
          height: "6' 4\"",
          weight: 192,
          "birth-place": "San Diego, CA, United States",
          shoots: "Left",
          birthday: "1995-12-08",
          "games-played": 37,
          goals: "18",
          assists: "13",
          points: "3",
        },
        {
          "player-name": "Quinn Hughes",
          "player-img": "Canucks_Quinn_Hughes.png",
          "team-number": 43,
          position: "Defencemen",
          height: "5' 10 \"",
          weight: 170,
          "birth-place": "Orlando, FL, United States",
          shoots: "Left",
          birthday: "1999-10-14",
          "games-played": 73,
          goals: "8",
          assists: "48",
          points: "56",
        },
        {
          "player-name": "Brock Boeser",
          "player-img": "Canucks_Boeser_Brock.png",
          "team-number": 6,
          position: "Right Wing",
          height: "6' 1 \"",
          weight: 201,
          "birth-place": "Burnsville, MN, USA",
          shoots: "Right",
          birthday: "1997-02-25",
          "games-played": 197,
          goals: "75",
          assists: "86",
          points: "161",
        },
        {
          "player-name": "Elias Pettersson",
          "player-img": "Canucks_Pettersson_Elias.png",
          "team-number": 40,
          position: "Center",
          height: "6' 2\"",
          weight: 176,
          "birth-place": "Sundsvall, Sweden",
          shoots: "Left",
          birthday: "1998-11-12",
          "games-played": 139,
          goals: "55",
          assists: "77",
          points: "132",
        },
      ],
    },
    capitals: {
      "franchise-name": "Capitals",
      "franchise-location": "Washington",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Nicklas Backstrom",
          "player-img": "Capitals_Backstrom_19.png",
          "team-number": 19,
          position: "Center",
          height: "6' 1\"",
          weight: 208,
          "birth-place": "Gavle, Sweden",
          shoots: "Left",
          birthday: "1987-11-23",
          "games-played": 956,
          goals: "243",
          assists: "684",
          points: "927",
        },
        {
          "player-name": "TJ Oshie",
          "player-img": "Capitals_Oshie_TJ.png",
          "team-number": 77,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 195,
          "birth-place": "Everett, WA, United States",
          shoots: "Right",
          birthday: "1986-12-23",
          "games-played": 803,
          goals: "238",
          assists: "329",
          points: "567",
        },
        {
          "player-name": "Alex Ovechkin",
          "player-img": "Capitals_Ovechkin_8.png",
          "team-number": 8,
          position: "Left Wing",
          height: "6' 3\"",
          weight: 230,
          "birth-place": "Moscow, Russia",
          shoots: "Right",
          birthday: "1985-09-17",
          "games-played": 1152,
          goals: "706",
          assists: "572",
          points: "1278",
        },
        {
          "player-name": "Michal Kempny",
          "player-img": "Kempny.png",
          "team-number": 6,
          position: "Defense",
          height: "6' 0 \"",
          weight: 194,
          "birth-place": "Hodonin, Czech Republic",
          shoots: "Left",
          birthday: "1990-09-08",
          "games-played": 232,
          goals: "14",
          assists: "47",
          points: "61",
        },
        {
          "player-name": "Tom Wilson",
          "player-img": "Capitals_Wilson_43.png",
          "team-number": 43,
          position: "Right Wing",
          height: "6' 4\"",
          weight: 210,
          "birth-place": "Toronto, ON, Canada",
          shoots: "Right",
          birthday: "1994-03-29",
          "games-played": 522,
          goals: "78",
          assists: "110",
          points: "188",
        },
        {
          "player-name": "John Carlson",
          "player-img": "Capitals_Carlson_74.png",
          "team-number": 74,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 212,
          "birth-place": "Natick, MA, United States",
          shoots: "Right",
          birthday: "1990-01-10",
          "games-played": 757,
          goals: "105",
          assists: "373",
          points: "478",
        },
      ],
    },
    coyotes: {
      "franchise-name": "Coyotes",
      "franchise-location": "Arizona",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Antti Raanta",
          "player-img": "Raanta.png",
          "team-number": 32,
          position: "Goalie",
          height: "6' 0\"",
          weight: 195,
          "birth-place": "Rauma, Finland",
          shoots: "Left",
          birthday: "1989-05-12",
          "games-played": 186,
          goals: "NA",
          assists: "NA",
          points: "NA",
        },
        {
          "player-name": "Oliver Ekman-Larsson",
          "player-img": "Coyotes_Ekman-Larsson_23.png",
          "team-number": 23,
          position: "Defenseman",
          height: "6' 2\"",
          weight: 200,
          "birth-place": "Karlskrona, Sweden",
          shoots: "Left",
          birthday: "1991-07-17",
          "games-played": 723,
          goals: "125",
          assists: "239",
          points: "364",
        },
        {
          "player-name": "Niklas Hjalmarsson",
          "player-img": "Hjalmarsson.png",
          "team-number": 4,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 197,
          "birth-place": "Eksjo, Sweden",
          shoots: "Left",
          birthday: "1987-06-06",
          "games-played": 780,
          goals: "25",
          assists: "142",
          points: "167",
        },
        {
          "player-name": "Christian Fischer",
          "player-img": "ChristianFischer.png",
          "team-number": 36,
          position: "Right Wing",
          height: "6' 2 \"",
          weight: 214,
          "birth-place": "Chicago, IL, USA",
          shoots: "Right",
          birthday: "1997-04-15",
          "games-played": 213,
          goals: "35",
          assists: "28",
          points: "63",
        },
        {
          "player-name": "Derek Stepan",
          "player-img": "Stepan.png",
          "team-number": 21,
          position: "Center",
          height: "6' 0\"",
          weight: 196,
          "birth-place": "Hastings, MN, USA",
          shoots: "Right",
          birthday: "1990-06-18",
          "games-played": 739,
          goals: "167",
          assists: "312",
          points: "479",
        },
        {
          "player-name": "Clayton Keller",
          "player-img": "ClaytonKeller.png",
          "team-number": 9,
          position: "Center",
          height: "5' 10 \"",
          weight: 170,
          "birth-place": "Chesterfield, MO, USA",
          shoots: "Left",
          birthday: "1998-07-29",
          "games-played": 237,
          goals: "54",
          assists: "104",
          points: "158",
        },
      ],
    },
    devils: {
      "franchise-name": "Devils",
      "franchise-location": "New Jersey",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "PK Subban",
          "player-img": "PK_Subban.png",
          "team-number": 76,
          position: "Defenseman",
          height: "6' 0\"",
          weight: 205,
          "birth-place": "Toronto, Ontario, CA",
          shoots: "Right",
          birthday: "1989-05-13",
          "games-played": 68,
          goals: "7",
          assists: "11",
          points: "18",
        },
        {
          "player-name": "Nico Hischier",
          "player-img": "Devils_Hischier_Nico.png",
          "team-number": 13,
          position: "Center",
          height: "6' 1\"",
          weight: 175,
          "birth-place": "Brig, Switzerland",
          shoots: "Left",
          birthday: "1999-01-04",
          "games-played": 209,
          goals: "51",
          assists: "84",
          points: "135",
        },
        {
          "player-name": "Kyle Palmieri",
          "player-img": "Palmieri.png",
          "team-number": 21,
          position: "Right Wing",
          height: "5' 10\"",
          weight: 190,
          "birth-place": "Smithtown, NY",
          shoots: "Left",
          birthday: "1991-02-01",
          "games-played": 561,
          goals: "175",
          assists: "163",
          points: "338",
        },
        {
          "player-name": "Jack Hughes",
          "player-img": "Jack_Hughes.png",
          "team-number": 86,
          position: "Center",
          height: "5' 11\"",
          weight: 170,
          "birth-place": "Orlando, FL, USA",
          birthday: "2001-05-14",
          "games-played": 61,
          goals: "7",
          assists: "14",
          points: "21",
        },
        {
          "player-name": "Travis Zajac",
          "player-img": "Zajac.png",
          "team-number": 19,
          position: "Center",
          height: "6' 2\"",
          weight: 195,
          "birth-place": "Winnipeg, MB, CAN",
          shoots: "Right",
          birthday: "1985-05-13",
          "games-played": 991,
          goals: "195",
          assists: "337",
          points: "532",
        },
        {
          "player-name": "Mackenzie Blackwood",
          "player-img": "Devils_Blackwood_Mackenzie.png",
          "team-number": 29,
          position: "Goalie",
          height: "6' 4\"",
          weight: 225,
          "birth-place": "Thunder Bay, ON, Canada",
          shoots: "Left",
          birthday: "1996-12-06",
          "games-played": 70,
          goals: "64",
          assists: "32",
          points: "24",
        },
      ],
    },
    ducks: {
      "franchise-name": "Ducks",
      "franchise-location": "Anaheim",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Cam Fowler",
          "player-img": "Ducks_Fowler_4.png",
          "team-number": 4,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 211,
          "birth-place": "Windsor, ON, Canada",
          shoots: "Left",
          birthday: "1991-12-05",
          "games-played": 679,
          goals: "67",
          assists: "234",
          points: "301",
        },
        {
          "player-name": "Hampus Lindholm",
          "player-img": "Ducks_Lindholm_47.png",
          "team-number": 47,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 205,
          "birth-place": "Helsingborg, Sweden",
          shoots: "Left",
          birthday: "1994-01-20",
          "games-played": 502,
          goals: "50",
          assists: "144",
          points: "194",
        },
        {
          "player-name": "Rickard Rakell",
          "player-img": "Rakell.png",
          "team-number": 67,
          position: "Left Wing",
          height: "6' 1 \"",
          weight: 202,
          "birth-place": "Sundbyberg, Sweden",
          shoots: "Right",
          birthday: "1993-05-04",
          "games-played": 447,
          goals: "129",
          assists: "154",
          points: "283",
        },
        {
          "player-name": "Jakob Silfverberg",
          "player-img": "Silfverberg.png",
          "team-number": 33,
          position: "Right Wing",
          height: "6' 1 \"",
          weight: 204,
          "birth-place": "Gavle, Sweden",
          shoots: "Right",
          birthday: "1990-10-13",
          "games-played": 558,
          goals: "138",
          assists: "153",
          points: "291",
        },
        {
          "player-name": "John Gibson",
          "player-img": "Ducks_Gibson_36.png",
          "team-number": 36,
          position: "Goalie",
          height: "6' 3\"",
          weight: 227,
          "birth-place": "Pittsburgh, Pennsylvania",
          shoots: "Left",
          birthday: "1993-07-14",
          "games-played": 287,
          goals: "NA",
          assists: "NA",
          points: "NA",
        },
        {
          "player-name": "Ryan Getzlaf",
          "player-img": "Ducks_Getzlaf_15.png",
          "team-number": 15,
          position: "Center",
          height: "6' 4\"",
          weight: 218,
          "birth-place": "Regina, SK, Canada",
          shoots: "Right",
          birthday: "1985-05-10",
          "games-played": 1053,
          goals: "274",
          assists: "691",
          points: "965",
        },
      ],
    },
    flames: {
      "franchise-name": "Flames",
      "franchise-location": "Calgary",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Mark Giordano",
          "player-img": "Flames_Giordano_5.png",
          "team-number": 5,
          position: "Defenceman",
          height: "6' 0\"",
          weight: 200,
          "birth-place": "Toronto, ON, Canada",
          shoots: "Left",
          birthday: "1983-10-03",
          "games-played": 893,
          goals: "134",
          assists: "349",
          points: "483",
        },
        {
          "player-name": "Sean Monahan",
          "player-img": "Flames_Monahan_23.png",
          "team-number": 23,
          position: "Center",
          height: "6' 2\"",
          weight: 185,
          "birth-place": "Brampton, ON, Canada",
          shoots: "Left",
          birthday: "1994-10-12",
          "games-played": 541,
          goals: "194",
          assists: "217",
          points: "411",
        },
        {
          "player-name": "Mikael Backlund",
          "player-img": "Flames_Backlund_Mikael.png",
          "team-number": 11,
          position: "Center",
          height: "6' 0\"",
          weight: 200,
          "birth-place": "Vasteras, Sweden",
          shoots: "Left",
          birthday: "1989-03-17",
          "games-played": 690,
          goals: "145",
          assists: "220",
          points: "365",
        },
        {
          "player-name": "Johnny Gaudreau",
          "player-img": "Flames_Gaudreau_13.png",
          "team-number": 13,
          position: "Left Wing",
          height: "5' 9\"",
          weight: 150,
          "birth-place": "Salem, NJ, United States",
          shoots: "Left",
          birthday: "1993-08-13",
          "games-played": 464,
          goals: "151",
          assists: "294",
          points: "445",
        },
        {
          "player-name": "Matthew Tkachuk",
          "player-img": "Flames_Tkachuk_Matthew.png",
          "team-number": 19,
          position: "Left Wing",
          height: "6' 2\"",
          weight: 202,
          "birth-place": "Scottsdale, AZ, United States",
          shoots: "Left",
          birthday: "1997-12-11",
          "games-played": 293,
          goals: "94",
          assists: "141",
          points: "235",
        },
        {
          "player-name": "David Rittich",
          "player-img": "Flames_Rittich_David.png",
          "team-number": 33,
          position: "Goalie",
          height: "6' 3 \"",
          weight: 206,
          "birth-place": "Jihlava, Czech Republic",
          shoots: "Left",
          birthday: "1992-08-19",
          "games-played": 115,
          goals: "106",
          assists: "59",
          points: "32",
        },
      ],
    },
    flyers: {
      "franchise-name": "Flyers",
      "franchise-location": "Philadelphia",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Jakub Voracek",
          "player-img": "Flyers_Voracek_93.png",
          "team-number": 93,
          position: "Right Wing",
          height: "6' 2\"",
          weight: 214,
          "birth-place": "Kladno, Czech Republic",
          shoots: "Left",
          birthday: "1989-08-15",
          "games-played": 915,
          goals: "207",
          assists: "488",
          points: "695",
        },
        {
          "player-name": "Carter Hart",
          "player-img": "carterhartheadshotEDIT.png",
          "team-number": 79,
          position: "Goalie",
          height: "6' 2 \"",
          weight: 181,
          "birth-place": "Sherwood Park, AB, Canada",
          shoots: "Left",
          birthday: "1998-08-13",
          "games-played": 74,
          goals: "40",
          assists: "26",
          points: "4",
        },
        {
          "player-name": "Claude Giroux",
          "player-img": "Flyers_Giroux_28.png",
          "team-number": 28,
          position: "Center",
          height: "5' 11\"",
          weight: 172,
          "birth-place": "Hearst, ON, Canada",
          shoots: "Right",
          birthday: "1988-01-12",
          "games-played": 889,
          goals: "257",
          assists: "558",
          points: "815",
        },
        {
          "player-name": "Ivan Provorov",
          "player-img": "Provorov.png",
          "team-number": 9,
          position: "Defense",
          height: "6' 1\"",
          weight: 201,
          "birth-place": "Yaroslavl, Russia",
          shoots: "Left",
          birthday: "1997-01-13",
          "games-played": 315,
          goals: "43",
          assists: "90",
          points: "133",
        },
        {
          "player-name": "Kevin Hayes",
          "player-img": "Flyers_Hayes_Kevin.png",
          "team-number": 13,
          position: "Center",
          height: "6' 5\"",
          weight: 216,
          "birth-place": "Dorchester, MA, United States",
          shoots: "Left",
          birthday: "1992-05-08",
          "games-played": 450,
          goals: "115",
          assists: "155",
          points: "270",
        },
        {
          "player-name": "Sean Couturier",
          "player-img": "Courturier.png",
          "team-number": 14,
          position: "Center",
          height: "6' 3\"",
          weight: 211,
          "birth-place": "Phoenix, AZ",
          shoots: "Left",
          birthday: "1992-12-07",
          "games-played": 647,
          goals: "156",
          assists: "246",
          points: "402",
        },
      ],
    },
    hurricanes: {
      "franchise-name": "Hurricanes",
      "franchise-location": "Carolina",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Brett Pesce",
          "player-img": "Brett_Pesce.png",
          "team-number": 22,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 206,
          "birth-place": "Tarrytown, NY, USA",
          shoots: "Right",
          birthday: "1994-11-15",
          "games-played": 50,
          goals: "20",
          assists: "82",
          points: "102",
        },
        {
          "player-name": "Jaccob Slavin",
          "player-img": "Slavin.png",
          "team-number": 74,
          position: "Defense",
          height: "6' 2\"",
          weight: 205,
          "birth-place": "Denver, Colorado",
          shoots: "Left",
          birthday: "1994-05-01",
          "games-played": 377,
          goals: "29",
          assists: "122",
          points: "151",
        },
        {
          "player-name": "Andre Svechnikov",
          "player-img": "Andre_Svechnikov.png",
          "team-number": 37,
          position: "Left Wing",
          height: "6' 2 \"",
          weight: 195,
          "birth-place": "Barnaul, Russia",
          shoots: "Left",
          birthday: "2000-03-26",
          "games-played": 150,
          goals: "44",
          assists: "54",
          points: "98",
        },
        {
          "player-name": "Sebastian Aho",
          "player-img": "SebastianAho.png",
          "team-number": 20,
          position: "Right Wing",
          height: "5' 11 \"",
          weight: 172,
          "birth-place": "Rauma, Finland",
          shoots: "Left",
          birthday: "1997-07-26",
          "games-played": 310,
          goals: "121",
          assists: "142",
          points: "263",
        },
        {
          "player-name": "Jordan Staal",
          "player-img": "Hurricanes_Staal_11.png",
          "team-number": 11,
          position: "Center",
          height: "6' 4\"",
          weight: 220,
          "birth-place": "Thunder Bay, ON, Canada",
          shoots: "Left",
          birthday: "1988-09-10",
          "games-played": 961,
          goals: 225,
          assists: "312",
          points: "537",
        },
        {
          "player-name": "Teuvo Teravainen",
          "player-img": "Teuvo.png",
          "team-number": 86,
          position: "Left Wing",
          height: "5' 11 \"",
          weight: 178,
          "birth-place": "Helsinki, Finland",
          shoots: "Left",
          birthday: "1994-09-11",
          "games-played": 428,
          goals: "91",
          assists: "198",
          points: "289",
        },
      ],
    },
    islanders: {
      "franchise-name": "Islanders",
      "franchise-location": "New York",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Nick Leddy",
          "player-img": "Islanders_Leddy.png",
          "team-number": 2,
          position: "Defenseman",
          height: "6' 0\"",
          weight: 212,
          "birth-place": "Eden Prairie, MN, United States",
          shoots: "Left",
          birthday: "1991-03-20",
          "games-played": 720,
          goals: "63",
          assists: "242",
          points: "305",
        },
        {
          "player-name": "Anders Lee",
          "player-img": "Islanders_Lee.png",
          "team-number": 27,
          position: "Left Wing",
          height: "6' 3 \"",
          weight: 231,
          "birth-place": "Edina, MN, United States",
          shoots: "Left",
          birthday: "1990-07-03",
          "games-played": 493,
          goals: "172",
          assists: "129",
          points: "301",
        },
        {
          "player-name": "Josh Bailey",
          "player-img": "Islanders_Bailey.png",
          "team-number": 12,
          position: "Right Wing",
          height: "6' 1\"",
          weight: 200,
          "birth-place": "Bowmanville, ON, Canada",
          shoots: "Left",
          birthday: "1989-10-02",
          "games-played": 865,
          goals: "154",
          assists: "322",
          points: "476",
        },
        {
          "player-name": "JG Pageau",
          "player-img": "Islanders_PageauHeadshot.png",
          "team-number": 44,
          position: "Center",
          height: "5' 10 \"",
          weight: 180,
          "birth-place": "Ottawa, ON, Canada",
          shoots: "Right",
          birthday: "1992-11-11",
          "games-played": 435,
          goals: "89",
          assists: "95",
          points: "184",
        },
        {
          "player-name": "Brock Nelson",
          "player-img": "Islanders_Nelson.png",
          "team-number": 29,
          position: "Center",
          height: "6' 3\"",
          weight: 212,
          "birth-place": "Warroad, MN, United States",
          shoots: "Left",
          birthday: "1991-10-15",
          "games-played": 548,
          goals: "150",
          assists: "145",
          points: "295",
        },
        {
          "player-name": "Mathew Barzal",
          "player-img": "Islanders_Barzal.png",
          "team-number": 13,
          position: "Center",
          height: "6' 0 \"",
          weight: 187,
          "birth-place": "Coquitlam, BC, Canada",
          shoots: "Right",
          birthday: "1997-05-26",
          "games-played": 234,
          goals: "59",
          assists: "148",
          points: "207",
        },
      ],
    },
    jets: {
      "franchise-name": "Jets",
      "franchise-location": "Winnipeg",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "Blake Wheeler",
          "player-img": "Jets_Wheeler_26.png",
          "team-number": 26,
          position: "Right Wing",
          height: "6' 5\"",
          weight: 225,
          "birth-place": "Plymouth, MN, United States",
          shoots: "Right",
          birthday: "1986-08-31",
          "games-played": 931,
          goals: "264",
          assists: "497",
          points: "761",
        },
        {
          "player-name": "Patrik Laine",
          "player-img": "Patrik_Laine.png",
          "team-number": 29,
          position: "Right Wing",
          height: "6' 5\"",
          weight: 206,
          "birth-place": "Tampere, Finland",
          shoots: "Right",
          birthday: "1998-14-19",
          "games-played": 305,
          goals: "138",
          assists: "109",
          points: "247",
        },
        {
          "player-name": "Adam Lowry",
          "player-img": "Jets_Lowry_17.png",
          "team-number": 17,
          position: "Left Wing",
          height: "6' 5\"",
          weight: 207,
          "birth-place": "St. Louis, MO, United States",
          shoots: "Left",
          birthday: "1993-03-29",
          "games-played": 408,
          goals: "57",
          assists: "66",
          points: "123",
        },
        {
          "player-name": "Josh Morrissey",
          "player-img": "Josh_Morrissey.png",
          "team-number": 44,
          position: "Defenceman",
          height: "6' 0\"",
          weight: 195,
          "birth-place": "Calgary, AB, Canada",
          shoots: "Left",
          birthday: "1995-03-28",
          "games-played": 288,
          goals: "24",
          assists: "84",
          points: "108",
        },
        {
          "player-name": "Mark Scheifele",
          "player-img": "Jets_Scheifele_55.png",
          "team-number": 55,
          position: "Center",
          height: "6' 3\"",
          weight: 198,
          "birth-place": "Kitchener, ON, Canada",
          shoots: "Right",
          birthday: "1993-03-15",
          "games-played": 519,
          goals: "180",
          assists: "264",
          points: "444",
        },
        {
          "player-name": "Connor Hellebuyck",
          "player-img": "ConnorHellebuyck.png",
          "team-number": 37,
          position: "Goalie",
          height: "6' 4 \"",
          weight: 207,
          "birth-place": "Commerce, MI, USA",
          shoots: "Left",
          birthday: "1993-05-19",
          "games-played": 270,
          goals: "NA",
          assists: "NA",
          points: "NA",
        },
      ],
    },
    kings: {
      "franchise-name": "Kings",
      "franchise-location": "Los Angeles",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Drew Doughty",
          "player-img": "Kings_Doughty_8.png",
          "team-number": 8,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 213,
          "birth-place": "London, ON, Canada",
          shoots: "Right",
          birthday: "1989-12-08",
          "games-played": 919,
          goals: "117",
          assists: "385",
          points: "502",
        },
        {
          "player-name": "Alex Iafallo",
          "player-img": "AlexIafallo.png",
          "team-number": 19,
          position: "Left Wing",
          height: "6' 0 \"",
          weight: 188,
          "birth-place": "Eden, NY, USA",
          shoots: "Left",
          birthday: "1993-12-21",
          "games-played": 227,
          goals: "41",
          assists: "60",
          points: "101",
        },
        {
          "player-name": "Adrian Kempe",
          "player-img": "Kempe.png",
          "team-number": 9,
          position: "Center",
          height: "6' 2 \"",
          weight: 201,
          "birth-place": "Kramfors, Sweden",
          shoots: "Left",
          birthday: "1996-09-13",
          "games-played": 256,
          goals: "41",
          assists: "62",
          points: "103",
        },
        {
          "player-name": "Dustin Brown",
          "player-img": "Kings_Brown_23.png",
          "team-number": 23,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 207,
          "birth-place": "Ithaca, NY, United States",
          shoots: "Right",
          birthday: "1984-11-04",
          "games-played": 1183,
          goals: "299",
          assists: "354",
          points: "653",
        },
        {
          "player-name": "Anze Kopitar",
          "player-img": "Kings_Kopitar_11.png",
          "team-number": 11,
          position: "Center",
          height: "6' 3\"",
          weight: 224,
          "birth-place": "Jesenice, Slovenia",
          shoots: "Left",
          birthday: "1987-08-24",
          "games-played": 1073,
          goals: "333",
          assists: "617",
          points: "950",
        },
        {
          "player-name": "Jonathan Quick",
          "player-img": "Kings_Quick_32.png",
          "team-number": 32,
          position: "Goalie",
          height: "6' 1\"",
          weight: 220,
          "birth-place": "Milford, CT, United States",
          shoots: "Left",
          birthday: "1986-01-21",
          "games-played": 644,
          goals: "636",
          assists: "325",
          points: "240",
        },
      ],
    },
    knights: {
      "franchise-name": "Golden Knights",
      "franchise-location": "Vegas",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Marc-Andre Fleury",
          "player-img": "Fleury.png",
          "team-number": 29,
          position: "Goalie",
          height: "6' 2\"",
          weight: 180,
          "birth-place": "Sorel, PQ",
          shoots: "Left",
          birthday: "1984-12-28",
          "games-played": 847,
          goals: "n/a",
          assists: "n/a",
          points: "n/a",
        },
        {
          "player-name": "Shea Theodore",
          "player-img": "VGK_Theodore_Shea.png",
          "team-number": 27,
          position: "Defensemen",
          height: "6' 2 \"",
          weight: 195,
          "birth-place": "Langley, BC, Canada",
          shoots: "Left",
          birthday: " 1995-08-03",
          "games-played": 264,
          goals: "36",
          assists: "93",
          points: "129",
        },
        {
          "player-name": "Reilly Smith",
          "player-img": "Smith.png",
          "team-number": 19,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 185,
          "birth-place": "Toronto, ON, Canada",
          shoots: "Left",
          birthday: "1991-04-01",
          "games-played": 577,
          goals: "144",
          assists: "210",
          points: "354",
        },
        {
          "player-name": "Mark Stone",
          "player-img": "MarkStone.png",
          "team-number": 61,
          position: "Right Wing",
          height: "6' 4 \"",
          weight: 219,
          "birth-place": "Winnipeg, MB, Canada",
          shoots: "Right",
          birthday: "1992-05-13",
          "games-played": 449,
          goals: "149",
          assists: "236",
          points: "385",
        },
        {
          "player-name": "Jonathan Marchessault",
          "player-img": "Marchessault.png",
          "team-number": 81,
          position: "Center",
          height: "5' 9\"",
          weight: 174,
          "birth-place": "Cap-Rouge, QC, CAN",
          shoots: "Right",
          birthday: "1990-12-27",
          "games-played": 349,
          goals: "112",
          assists: "139",
          points: "251",
        },
        {
          "player-name": "Brayden McNabb",
          "player-img": "McNabb.png",
          "team-number": 3,
          position: "Defense",
          height: "6' 4\"",
          weight: 216,
          "birth-place": "Davidson, SASK",
          shoots: "Left",
          birthday: "1986-01-21",
          "games-played": 466,
          goals: "18",
          assists: "72",
          points: "90",
        },
      ],
    },
    lightning: {
      "franchise-name": "Lightning",
      "franchise-location": "Tampa Bay",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Andrei Vasilevskiy",
          "player-img": "Lightning_Vasilevskiy_88.png",
          "team-number": 88,
          position: "Goalie",
          height: "6' 3\"",
          weight: 207,
          "birth-place": "Tyumen, Russia",
          shoots: "Left",
          birthday: "1994-07-25",
          "games-played": 230,
          goals: "159",
          assists: "73",
          points: "18",
        },
        {
          "player-name": "Victor Hedman",
          "player-img": "Lightning_Hedman_77.png",
          "team-number": 77,
          position: "Defenseman",
          height: "6' 6\"",
          weight: 230,
          "birth-place": "Ornskoldsvik, Sweden",
          shoots: "Left",
          birthday: "1990-12-18",
          "games-played": 762,
          goals: "105",
          assists: "368",
          points: "473",
        },
        {
          "player-name": "Ryan McDonagh",
          "player-img": "McDonagh.png",
          "team-number": 27,
          position: "Defense",
          height: "6' 1 \"",
          weight: 215,
          "birth-place": "St. Paul, MN, USA",
          shoots: "Left",
          birthday: "1989-06-13",
          "games-played": 662,
          goals: "63",
          assists: "236",
          points: "299",
        },
        {
          "player-name": "Brayden Point",
          "player-img": "Bay_Point_Brayden.png",
          "team-number": 21,
          position: "Center",
          height: "5' 10\"",
          weight: 166,
          "birth-place": "Calgary, AB, Canada",
          shoots: "Right",
          birthday: "1996-03-13",
          "games-played": 66,
          goals: "25",
          assists: "39",
          points: "64",
        },
        {
          "player-name": "Steven Stamkos",
          "player-img": "Lightning_Stamkos_91.png",
          "team-number": 91,
          position: "Center",
          height: "6' 1\"",
          weight: 194,
          "birth-place": "Markham, ON, Canada",
          shoots: "Right",
          birthday: "1990-02-07",
          "games-played": 803,
          goals: "422",
          assists: "410",
          points: "832",
        },
        {
          "player-name": "Nikita Kucherov",
          "player-img": "Bay_Kucherov_Nikita.png",
          "team-number": 86,
          position: "Right Wing",
          height: "5' 11\"",
          weight: 183,
          "birth-place": "Maykop, Russia",
          shoots: "Left",
          birthday: "1993-06-17",
          "games-played": 68,
          goals: "33",
          assists: "52",
          points: "85",
        },
      ],
    },
    mapleleafs: {
      "franchise-name": "Maple Leafs",
      "franchise-location": "Toronto",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "Morgan Rielly",
          "player-img": "MapleLeafs_Rielly_44.png",
          "team-number": 44,
          position: "Defenceman",
          height: "6' 1\"",
          weight: 217,
          "birth-place": "Vancouver, BC, Canada",
          shoots: "Left",
          birthday: "1994-03-09",
          "games-played": 517,
          goals: "54",
          assists: "216",
          points: "270",
        },
        {
          "player-name": "Justin Holl",
          "player-img": "Leafs_Justin_Holl_2020.png",
          "team-number": 3,
          position: "Defenceman",
          height: "6' 4 \"",
          weight: 210,
          "birth-place": "Tonka Bay, MN, United States",
          shoots: "Right",
          birthday: "1992-01-30",
          "games-played": 81,
          goals: "4",
          assists: "17",
          points: "21",
        },
        {
          "player-name": "Frederik Andersen",
          "player-img": "MapleLeafs_Andersen_31.png",
          "team-number": 31,
          position: "Goalie",
          height: "6' 4\"",
          weight: 220,
          "birth-place": "Heming, Denmark",
          shoots: "Left",
          birthday: "1989-10-02",
          "games-played": 369,
          goals: "NA",
          assists: "NA",
          points: "NA",
        },
        {
          "player-name": "Zach Hyman",
          "player-img": "Hyman.png",
          "team-number": 11,
          position: "Left Wing",
          height: "6' 1 \"",
          weight: 209,
          "birth-place": "Toronto, ON, Canada",
          shoots: "Right",
          birthday: "1992-06-09",
          "games-played": 302,
          goals: "71",
          assists: "81",
          points: "152",
        },
        {
          "player-name": "John Tavares",
          "player-img": "TavaresLeafs.png",
          "team-number": 91,
          position: "Center",
          height: "6' 1\"",
          weight: 195,
          "birth-place": "Mississauga, ON, Canada",
          shoots: "Right",
          birthday: "1990-09-20",
          "games-played": 814,
          goals: "324",
          assists: "424",
          points: "769",
        },
        {
          "player-name": "Auston Matthews",
          "player-img": "MapleLeafs-Matthews-34.png",
          "team-number": 34,
          position: "Center",
          height: "6' 3\"",
          weight: 216,
          "birth-place": "Scottsdale, AZ, United States",
          shoots: "Left",
          birthday: "1997-09-17",
          "games-played": 282,
          goals: "158",
          assists: "127",
          points: "285",
        },
      ],
    },
    oilers: {
      "franchise-name": "Oilers",
      "franchise-location": "Edmonton",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "James Neal",
          "player-img": "Oilers_James_Neal.png",
          "team-number": 18,
          position: "Left Wing",
          height: "6' 3\"",
          weight: 212,
          "birth-place": "Whitby, ON, Canada",
          shoots: "Left",
          birthday: "1987-07-03",
          "games-played": 821,
          goals: "289",
          assists: "256",
          points: "545",
        },
        {
          "player-name": "Connor McDavid",
          "player-img": "Oilers_McDavid_97.png",
          "team-number": 97,
          position: "Center",
          height: "6' 1\"",
          weight: 190,
          "birth-place": "Richmond Hill, ON, Canada",
          shoots: "Left",
          birthday: "1997-01-13",
          "games-played": 351,
          goals: "162",
          assists: "307",
          points: "469",
        },
        {
          "player-name": "Leon Draisaitl",
          "player-img": "Leon.png",
          "team-number": 29,
          position: "Right Wing",
          height: "6' 1\"",
          weight: 214,
          "birth-place": "Cologne, Germany",
          shoots: "Left",
          birthday: "1995-10-27",
          "games-played": 422,
          goals: "168",
          assists: "254",
          points: "422",
        },
        {
          "player-name": "Oscar Klefbom",
          "player-img": "Oilers_Klefbom_84.png",
          "team-number": 84,
          position: "Defenceman",
          height: "6' 3\"",
          weight: 210,
          "birth-place": "Karlstad, Sweden",
          shoots: "Left",
          birthday: "1993-07-20",
          "games-played": 378,
          goals: "34",
          assists: "122",
          points: "156",
        },
        {
          "player-name": "Adam Larsson",
          "player-img": "Oilers_Larsson_6.png",
          "team-number": 6,
          position: "Defenceman",
          height: "6' 3\"",
          weight: 205,
          "birth-place": "Skelleftea, Sweden",
          shoots: "Right",
          birthday: "1992-11-12",
          "games-played": 547,
          goals: "21",
          assists: "106",
          points: "127",
        },
        {
          "player-name": "Mikko Koskinen",
          "player-img": "MikkoKoskinen.png",
          "team-number": 19,
          position: "Goalie",
          height: "6' 7 \"",
          weight: 202,
          "birth-place": "Vantaa, Finland",
          shoots: "Left",
          birthday: "1988-07-18",
          "games-played": 97,
          goals: "89",
          assists: "45",
          points: "35",
        },
      ],
    },
    panthers: {
      "franchise-name": "Panthers",
      "franchise-location": "Florida",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Aaron Ekblad",
          "player-img": "Panthers_Ekblad_5.png",
          "team-number": 5,
          position: "Defenseman",
          height: "6' 4\"",
          weight: 216,
          "birth-place": "Windsor, ON, Canada",
          shoots: "Right",
          birthday: "1996-02-07",
          "games-played": 458,
          goals: "71",
          assists: "141",
          points: "212",
        },
        {
          "player-name": "Keith Yandle",
          "player-img": "Panthers_Yandle.png",
          "team-number": 3,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 192,
          "birth-place": "Boston, MA, United States",
          shoots: "Left",
          birthday: "1996-09-09",
          "games-played": 976,
          goals: "99",
          assists: "474",
          points: "573",
        },
        {
          "player-name": "Jonathan Huberdeau",
          "player-img": "Panthers_Huberdeau_11.png",
          "team-number": 11,
          position: "Left Wing",
          height: "6' 1\"",
          weight: 188,
          "birth-place": "Saint-Jerome, QC, Canada",
          shoots: "Left",
          birthday: "1993-06-04",
          "games-played": 536,
          goals: "148",
          assists: "289",
          points: "437",
        },
        {
          "player-name": "Sergei Bobrovsky",
          "player-img": "Sergei_Bobrovsky.png",
          "team-number": 72,
          position: "Goalie",
          height: "6' 2\"",
          weight: 187,
          "birth-place": "Novokuznetsk, Russia",
          shoots: "Left",
          birthday: "1988-09-20",
          "games-played": 507,
          goals: "278",
          assists: "172",
          points: "43",
        },
        {
          "player-name": "Aleksander Barkov",
          "player-img": "Panthers_Barkov_16.png",
          "team-number": 16,
          position: "Center",
          height: "6' 3\"",
          weight: 213,
          "birth-place": "Tampere, Finland",
          shoots: "Left",
          birthday: "1995-09-02",
          "games-played": 479,
          goals: "155",
          assists: "252",
          points: "407",
        },
        {
          "player-name": "Patric Hornqvist",
          "player-img": "Panthers_Hornqvist.png",
          "team-number": 70,
          position: "Right Wing",
          height: "5' 11 \"",
          weight: 189,
          "birth-place": "Sollentuna, Sweden",
          shoots: "Right",
          birthday: "1987-01-01",
          "games-played": 770,
          goals: "238",
          assists: "242",
          points: "480 ",
        },
      ],
    },
    penguins: {
      "franchise-name": "Penguins",
      "franchise-location": "Pittsburgh",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Evgeni Malkin",
          "player-img": "Penguins_Malkin_Evgeni_02.png",
          "team-number": 71,
          position: "Center",
          height: "6' 3\"",
          weight: 195,
          "birth-place": "Magnitogorsk, Russia",
          shoots: "Left",
          birthday: "1986-07-31",
          "games-played": 907,
          goals: "416",
          assists: "660",
          points: "1076",
        },
        {
          "player-name": "Kris Letang",
          "player-img": "Penguins_Letang_Kris_02.png",
          "team-number": 58,
          position: "Defenseman",
          height: "6' 0\"",
          weight: 201,
          "birth-place": "Montreal, QC, Canada",
          shoots: "Right",
          birthday: "1987-04-24",
          "games-played": 808,
          goals: "127",
          assists: "410",
          points: "537",
        },
        {
          "player-name": "Jake Guentzel",
          "player-img": "Penguins_Guentzel_Jake_02.png",
          "team-number": 59,
          position: "Left Wing",
          height: "5' 11 \"",
          weight: 180,
          "birth-place": "Omaha, NE, USA",
          shoots: "Left",
          birthday: "1994-10-06",
          "games-played": 243,
          goals: "98",
          assists: "102",
          points: "200",
        },
        {
          "player-name": "Brian Dumoulin",
          "player-img": "Penguins_Dumoulin_Brian_03.png",
          "team-number": 8,
          position: "Defense",
          height: "6' 4 \"",
          weight: 207,
          "birth-place": "Biddeford, ME, USA",
          shoots: "Left",
          birthday: "1991-09-06",
          "games-played": 347,
          goals: "11",
          assists: "71",
          points: "82",
        },
        {
          "player-name": "Sidney Crosby",
          "player-img": "Penguins_Crosby_Sidney_01.png",
          "team-number": 87,
          position: "Center",
          height: "5' 11\"",
          weight: 200,
          "birth-place": "Cole Harbour, NS, Canada",
          shoots: "Left",
          birthday: "1987-08-07",
          "games-played": 984,
          goals: "462",
          assists: "801",
          points: "1263",
        },
        {
          "player-name": "Tristan Jarry",
          "player-img": "Penguins_Jarry_Tristan_03.png",
          "team-number": 35,
          position: "Goalie",
          height: "6' 2\"",
          weight: 194,
          "birth-place": "Surrey, BC, Canada",
          shoots: "Left",
          birthday: "1995-03-29",
          "games-played": 62,
          goals: "57",
          assists: "34",
          points: "20",
        },
      ],
    },
    predators: {
      "franchise-name": "Predators",
      "franchise-location": "Nashville",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Matt Duchene",
          "player-img": "Duchene.png",
          "team-number": 95,
          position: "Center",
          height: "5' 11 \"",
          weight: 195,
          "birth-place": "Haliburton, ON, Canada",
          shoots: "Left",
          birthday: "1991-01-16",
          "games-played": 793,
          goals: "245",
          assists: "344",
          points: "589",
        },
        {
          "player-name": "Roman Josi",
          "player-img": "Predators_Josi_59.png",
          "team-number": 59,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 192,
          "birth-place": "Bern, Switzerland",
          shoots: "Left",
          birthday: "1990-06-01",
          "games-played": 632,
          goals: "109",
          assists: "304",
          points: "413",
        },
        {
          "player-name": "Ryan Ellis",
          "player-img": "Ryan.png",
          "team-number": 4,
          position: "Defense",
          height: "5' 10\"",
          weight: 180,
          "birth-place": "Hamilton, ON, Canada",
          shoots: "Right",
          birthday: "1991-01-03",
          "games-played": 527,
          goals: "70",
          assists: "182",
          points: "252",
        },
        {
          "player-name": "Filip Forsberg",
          "player-img": "Predators_Forsberg_9.png",
          "team-number": 9,
          position: "Center",
          height: "6' 1\"",
          weight: 186,
          "birth-place": "Ostervala, Sweden",
          shoots: "Right",
          birthday: "1994-08-13",
          "games-played": 458,
          goals: "166",
          assists: "187",
          points: "353",
        },
        {
          "player-name": "Pekka Rinne",
          "player-img": "Predators_Rinne_35.png",
          "team-number": 35,
          position: "Goalie",
          height: "6' 5\"",
          weight: 204,
          "birth-place": "Kempele, Finland",
          shoots: "Left",
          birthday: "1982-11-03",
          "games-played": 659,
          goals: "NA",
          assists: "NA",
          points: "NA",
        },
        {
          "player-name": "Mattias Ekholm",
          "player-img": "Mattias.png",
          "team-number": 14,
          position: "Defense",
          height: "6' 4\"",
          weight: 215,
          "birth-place": "Borlange, Sweden",
          shoots: "Left",
          birthday: "1990-05-24",
          "games-played": 538,
          goals: "45",
          assists: "151",
          points: "196",
        },
      ],
    },
    czech: {
      "franchise-name": "Czech",
      "franchise-location": "Czech Republic",
      country: "CZ",
      locale: "en-US",
      players: [
        {
          "player-name": "David Rittich",
          "player-img": "2.png",
          "team-number": 33,
          position: "Goalie",
          height: "6' 3\"",
          weight: 206,
          "birth-place": "Jihlava, Czech Republic",
          shoots: "Left",
          birthday: "1992-08-19",
          "games-played": 115,
          goals: "106",
          assists: "",
          points: "",
        },
        {
          "player-name": "David Pastrnak",
          "player-img": "1.png",
          "team-number": 88,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 194,
          "birth-place": "Havirov, Czech Republic",
          shoots: "Right",
          birthday: "1996-05-25",
          "games-played": 390,
          goals: "180",
          assists: "190",
          points: "379",
        },
        {
          "player-name": "Dominik Kubalik",
          "player-img": "3.png",
          "team-number": 8,
          position: "Left Wing",
          height: "6' 2\"",
          weight: 179,
          "birth-place": "Plzen, Czech Republic",
          shoots: "Left",
          birthday: "1995-08-21",
          "games-played": 68,
          goals: "30",
          assists: "16",
          points: "46",
        },
        {
          "player-name": "Jakub Voracek",
          "player-img": "4.png",
          "team-number": 93,
          position: "Right Wing",
          height: "6' 2\"",
          weight: 214,
          "birth-place": "Kladno, Czech Republic",
          shoots: "Left",
          birthday: "1989-08-15",
          "games-played": 907,
          goals: "215",
          assists: "488",
          points: "695",
        },
        {
          "player-name": "Ondrej Palat",
          "player-img": "5.png",
          "team-number": 18,
          position: "Left Wing",
          height: "6' 0\"",
          weight: 194,
          "birth-place": "Frydek-Mistek, Czech Republic",
          shoots: "Left",
          birthday: "1991-03-28",
          "games-played": 496,
          goals: "110",
          assists: "218",
          points: "328",
        },
        {
          "player-name": "Tomas Hertl ",
          "player-img": "6.png",
          "team-number": 48,
          position: "Center",
          height: "6' 2\"",
          weight: 215,
          "birth-place": "FPraha, Czech Republic",
          shoots: "Left",
          birthday: "1993-11-12",
          "games-played": 453,
          goals: "132",
          assists: "148",
          points: "280",
        },
      ],
    },
    rangers: {
      "franchise-name": "Rangers",
      "franchise-location": "New York",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Igor Shesterkin",
          "player-img": "NY_Rangers_Shestyorkin_Igor.png",
          "team-number": 31,
          position: "Goalie",
          height: "6' 2\"",
          weight: 182,
          "birth-place": "Moscow, Russia",
          shoots: "Left",
          birthday: "1995-12-30",
          "games-played": 12,
          goals: "",
          assists: "",
          points: "",
        },
        {
          "player-name": "Kaapo Kakko",
          "player-img": "NY_Rangers_Kakko_Kaapo.png",
          "team-number": 24,
          position: "Right Wing",
          height: "6' 3\"",
          weight: 199,
          "birth-place": "Turku, Finland",
          shoots: "Left",
          birthday: "2001-02-13",
          "games-played": 66,
          goals: "10",
          assists: "13",
          points: "23",
        },
        {
          "player-name": "Adam Fox",
          "player-img": "NY_Rangers_Fox_Adam.png",
          "team-number": 23,
          position: "Defensemen",
          height: "5' 11\"",
          weight: 181,
          "birth-place": "Jericho, NY, United States",
          shoots: "Right",
          birthday: "1998-12-17",
          "games-played": 70,
          goals: "8",
          assists: "34",
          points: "42",
        },
        {
          "player-name": "Chris Krider",
          "player-img": "NY_Rangers_Kreider_Chris.png",
          "team-number": 20,
          position: "Left Wing",
          height: "6' 3\"",
          weight: 217,
          "birth-place": "Boxford, MA, United States",
          shoots: "Left",
          birthday: "1991-04-30",
          "games-played": 523,
          goals: "157",
          assists: "159",
          points: "316",
        },
        {
          "player-name": "Artemi Panarin",
          "player-img": "NY_Rangers_Panarin_Artemi.png",
          "team-number": 10,
          position: "Left Wing",
          height: "5' 11\"",
          weight: 170,
          "birth-place": "Korkino, Russia",
          shoots: "Right",
          birthday: "1991-10-30",
          "games-played": 391,
          goals: "148",
          assists: "267",
          points: "415",
        },
        {
          "player-name": "Mika Zibanejad",
          "player-img": "NY_Rangers_Zibanejad_Mika.png",
          "team-number": 93,
          position: "Center",
          height: "6' 2\"",
          weight: 208,
          "birth-place": "Huddinge, Sweden",
          shoots: "Right",
          birthday: "1993-04-18",
          "games-played": 548,
          goals: "176",
          assists: "208",
          points: "384",
        },
      ],
    },
    redwings: {
      "franchise-name": "Red Wings",
      "franchise-location": "Detroit",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Jonathan Bernier",
          "player-img": "Red_Wings_Jonathan_Bernier.png",
          "team-number": 45,
          position: "Goalie",
          height: "6'0\"",
          weight: 185,
          "birth-place": "Laval, QC, Canada",
          shoots: "Left",
          birthday: "1988-08-07",
          "games-played": 370,
          goals: "",
          assists: "",
          points: "",
        },
        {
          "player-name": "Dylan Larkin",
          "player-img": "RedWings_Larkin_71.png",
          "team-number": 71,
          position: "Center",
          height: "6'1\"",
          weight: 190,
          "birth-place": "Waterford, Michigan",
          shoots: "Left",
          birthday: "1996-07-30",
          "games-played": 389,
          goals: "107",
          assists: "159",
          points: "266",
        },
        {
          "player-name": "Filip Hronek",
          "player-img": "Red_Wings_Hronek_Filip.png",
          "team-number": 17,
          position: "Defenseman",
          height: "6'0\"",
          weight: 183,
          "birth-place": "Hradec Králové, Czech Republic",
          shoots: "Right",
          birthday: "1997-11-02",
          "games-played": 111,
          goals: "14",
          assists: "40",
          points: "54",
        },
        {
          "player-name": "Frans Nielsen",
          "player-img": "Frans_Nielsen.png",
          "team-number": 81,
          position: "Center",
          height: "6'1\"",
          weight: 186,
          "birth-place": "Herning, Denmark",
          shoots: "Left",
          birthday: "1984-04-24",
          "games-played": 896,
          goals: "166",
          assists: "301",
          points: "467",
        },
        {
          "player-name": "Tyler Bertuzzi",
          "player-img": "Tyler_Bertuzzi.png",
          "team-number": 59,
          position: "Left Wing",
          height: "6'1\"",
          weight: 199,
          "birth-place": "Sudbury, ON, Canada",
          shoots: "Left",
          birthday: "1995-02-24",
          "games-played": 199,
          goals: "49",
          assists: "70",
          points: "119",
        },
        {
          "player-name": "Luke Glendening",
          "player-img": "Luke_Glendening.png",
          "team-number": 39,
          position: "Center",
          height: "5' 11 \"",
          weight: 191,
          "birth-place": "Grand Rapids, MI, USA",
          shoots: "Right",
          birthday: "1989-04-28",
          "games-played": 500,
          goals: "51",
          assists: "60",
          points: "111",
        },
      ],
    },
    sabres: {
      "franchise-name": "Sabres",
      "franchise-location": "Buffalo",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Sam Reinhart",
          "player-img": "Sam_Reinhart.png",
          "team-number": 23,
          position: "Center",
          height: "6' 1\"",
          weight: 194,
          "birth-place": "West Vancouver, BC, Canada",
          shoots: "Right",
          birthday: "1995-11-06",
          "games-played": 400,
          goals: "109",
          assists: "146",
          points: "255",
        },
        {
          "player-name": "Jake McCabe",
          "player-img": "JakeMcCabe.png",
          "team-number": 19,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 210,
          "birth-place": "Eau Claire, WI, USA",
          shoots: "Left",
          birthday: "1993-10-12",
          "games-played": 340,
          goals: "17",
          assists: "57",
          points: "74",
        },
        {
          "player-name": "Rasmus Dahlin",
          "player-img": "Rasmus.png",
          "team-number": 26,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 190,
          "birth-place": "Lidkoping, Sweden",
          shoots: "Left",
          birthday: "2000-04-13",
          "games-played": 141,
          goals: "13",
          assists: "71",
          points: "84",
        },
        {
          "player-name": "Kyle Okposo",
          "player-img": "Okposo.png",
          "team-number": 21,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 220,
          "birth-place": "St. Paul, MN, USA",
          shoots: "RIght",
          birthday: "1988-04-16",
          "games-played": 800,
          goals: "196",
          assists: "310",
          points: "506",
        },
        {
          "player-name": "Jack Eichel",
          "player-img": "Eichel.png",
          "team-number": 9,
          position: "Center",
          height: "6' 2\"",
          weight: 196,
          "birth-place": "North Chelmsford, Massachusetts, USA",
          shoots: "Right",
          birthday: "1996-10-28",
          "games-played": 354,
          goals: "137",
          assists: "200",
          points: "337",
        },
        {
          "player-name": "Carter Hutton",
          "player-img": "carterhutton.png",
          "team-number": 40,
          position: "Goalie",
          height: "6' 1 \"",
          weight: 202,
          "birth-place": "Thunder Bay, ON, Canada",
          shoots: "Left",
          birthday: "1985-12-19",
          "games-played": 219,
          goals: "0",
          assists: "0",
          points: "0 ",
        },
      ],
    },
    senators: {
      "franchise-name": "Senators",
      "franchise-location": "Ottawa",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "Erik Gudbranson",
          "player-img": "Senators_Gudbranson_Erik.png",
          "team-number": 44,
          position: "Defencemen",
          height: "6'5\"",
          weight: 217,
          "birth-place": "Ottawa, ON, Canada",
          shoots: "Right",
          birthday: "1992-01-07",
          "games-played": 518,
          goals: "20",
          assists: "53",
          points: "73",
        },
        {
          "player-name": "Brady Tkachuk",
          "player-img": "BradytkachukEDIT.png",
          "team-number": 7,
          position: "Left Wing",
          height: "6' 3 \"",
          weight: 196,
          "birth-place": "Scottsdale, Arizona",
          shoots: "Left",
          birthday: "1999-09-16",
          "games-played": 142,
          goals: "43",
          assists: "46",
          points: "89",
        },
        {
          "player-name": "Colin White",
          "player-img": "White.png",
          "team-number": 36,
          position: "Center",
          height: "6' 0 \"",
          weight: 183,
          "birth-place": "Boston, MA, USA",
          shoots: "Right",
          birthday: "1997-01-30",
          "games-played": 155,
          goals: "23",
          assists: "47",
          points: "70",
        },
        {
          "player-name": "Matt Murray",
          "player-img": "Senators_Murray_Matt.png",
          "team-number": 30,
          position: "Goalie",
          height: "6'4\"",
          weight: 178,
          "birth-place": "Thunderbay, ON, Canada",
          shoots: "Left",
          birthday: "1984-05-25",
          "games-played": 199,
          goals: "117",
          assists: "53",
          points: "19",
        },
        {
          "player-name": "Christian Wolanin",
          "player-img": "Senators_Wolanin.png",
          "team-number": 24,
          position: "Defenceman",
          height: "6'2\"",
          weight: 185,
          "birth-place": "Quebec City, QB, Canada",
          shoots: "Left",
          birthday: "1995-03-17",
          "games-played": 43,
          goals: "05",
          assists: "10",
          points: "15",
        },
        {
          "player-name": "Thomas Chabot",
          "player-img": "ChabotHeadshotEDIT.png",
          "team-number": 72,
          position: "Defenceman",
          height: "6' 2 \"",
          weight: 196,
          "birth-place": "Sainte-Marie, QC, Canada",
          shoots: "Left",
          birthday: "1997-01-30",
          "games-played": 205,
          goals: "29",
          assists: "90",
          points: "119",
        },
      ],
    },
    sharks: {
      "franchise-name": "Sharks",
      "franchise-location": "San Jose",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Logan Couture",
          "player-img": "Sharks_Couture_Headshot.png",
          "team-number": 39,
          position: "Center",
          height: "6' 1\"",
          weight: 200,
          "birth-place": "Guelph, ON, Canada",
          shoots: "Left",
          birthday: "1989-03-28",
          "games-played": 715,
          goals: "256",
          assists: "290",
          points: "546",
        },
        {
          "player-name": "Evander Kane",
          "player-img": "Kane.png",
          "team-number": 9,
          position: "Left Wing",
          height: "6' 2 \"",
          weight: 210,
          "birth-place": "Vancouver, BC, Canada",
          shoots: "Left",
          birthday: "1991-08-02",
          "games-played": 713,
          goals: "242",
          assists: "215",
          points: "457",
        },
        {
          "player-name": "Tomas Hertl",
          "player-img": "Sharks_Hertl_Headshot.png",
          "team-number": 48,
          position: "Center",
          height: "6' 2\"",
          weight: 210,
          "birth-place": "Praha, Czech Republic",
          shoots: "Left",
          birthday: "1993-11-12",
          "games-played": 453,
          goals: "132",
          assists: "148",
          points: "280",
        },
        {
          "player-name": "Erik Karlsson",
          "player-img": "Karlsson.png",
          "team-number": 65,
          position: "Defense",
          height: "6' 0 \"",
          weight: 190,
          "birth-place": "Landsbro, Sweden",
          shoots: "Right",
          birthday: "1990-05-31",
          "games-played": 736,
          goals: "135",
          assists: "468",
          points: "603",
        },
        {
          "player-name": "Brent Burns",
          "player-img": "Sharks_Burns_Headshot.png",
          "team-number": 88,
          position: "Defenseman",
          height: "6' 5\"",
          weight: 230,
          "birth-place": "Barrie, ON, Canada",
          shoots: "Right",
          birthday: "1985-03-09",
          "games-played": 1113,
          goals: "210",
          assists: "484",
          points: "694",
        },
        {
          "player-name": "Martin Jones",
          "player-img": "Sharks_Jones_Headshot.png",
          "team-number": 31,
          position: "Goalie",
          height: "6' 4\"",
          weight: 190,
          "birth-place": "North Vancouver, BC, Canada",
          shoots: "Left",
          birthday: "1990-01-10",
          "games-played": 327,
          goals: "NA",
          assists: "NA",
          points: "NA",
        },
      ],
    },
    stars: {
      "franchise-name": "Stars",
      "franchise-location": "Dallas",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Jamie Benn",
          "player-img": "Stars_Benn_14.png",
          "team-number": 14,
          position: "Left Wing",
          height: "6' 2\"",
          weight: 210,
          "birth-place": "Victoria, BC, Canada",
          shoots: "Left",
          birthday: "1989-07-18",
          "games-played": 814,
          goals: "300",
          assists: "388",
          points: "688",
        },
        {
          "player-name": "Alexander Radulov",
          "player-img": "AlexanderRadulov.png",
          "team-number": 47,
          position: "Right Wing",
          height: "6' 1 \"",
          weight: 201,
          "birth-place": "Nizhny Tagil, Russia",
          shoots: "Left",
          birthday: "1986-04-05",
          "games-played": 442,
          goals: "136",
          assists: "198",
          points: "334",
        },
        {
          "player-name": "Tyler Seguin",
          "player-img": "Stars_Seguin_91.png",
          "team-number": 91,
          position: "Center",
          height: "6' 1\"",
          weight: 200,
          "birth-place": "Brampton, ON, Canada",
          shoots: "Right",
          birthday: "1992-01-31",
          "games-played": 741,
          goals: "279",
          assists: "356",
          points: "635",
        },
        {
          "player-name": "John Klingberg",
          "player-img": "Stars_Klingberg_3.png",
          "team-number": 3,
          position: "Defenseman",
          height: "6' 2\"",
          weight: 180,
          "birth-place": "Gothenburg, Sweden",
          shoots: "Right",
          birthday: "1992-08-14",
          "games-played": 425,
          goals: "58",
          assists: "233",
          points: "291",
        },
        {
          "player-name": "Miro Heiskanen",
          "player-img": "Heiskanen.png",
          "team-number": 4,
          position: "Defense",
          height: "6' 1 \"",
          weight: 185,
          "birth-place": "Espoo, Finland",
          shoots: "Left",
          birthday: "1999-07-18",
          "games-played": 150,
          goals: "20",
          assists: "48",
          points: "68",
        },
        {
          "player-name": "Ben Bishop",
          "player-img": "Bishop.png",
          "team-number": 30,
          position: "Goalie",
          height: "6' 7\"",
          weight: 216,
          "birth-place": "Denver, Colorado",
          shoots: "Left",
          birthday: "1986-11-21",
          "games-played": 413,
          goals: "NA",
          assists: "NA",
          points: "NA",
        },
      ],
    },
    wild: {
      "franchise-name": "Wild",
      "franchise-location": "Minnesota",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Matt Dumba",
          "player-img": "Dumba.png",
          "team-number": 26,
          position: "Defenseman",
          height: "6' 0\"",
          weight: 189,
          "birth-place": "Regina, SASK, Canada",
          shoots: "Right",
          birthday: "1994-07-25",
          "games-played": 411,
          goals: "62",
          assists: "112",
          points: "174",
        },
        {
          "player-name": "Kevin Fiala",
          "player-img": "Kevin_Fiala.png",
          "team-number": 22,
          position: "Left Wing",
          height: "5' 10 \"",
          weight: 193,
          "birth-place": "St. Gallen, CHE",
          shoots: "Left",
          birthday: "1996-07-22",
          "games-played": 287,
          goals: "71",
          assists: "87",
          points: "158",
        },
        {
          "player-name": "Ryan Suter",
          "player-img": "Wild_Suter_20.png",
          "team-number": 20,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 200,
          "birth-place": "Madison, WI, United States",
          shoots: "Left",
          birthday: "1985-01-21",
          "games-played": 1142,
          goals: "90",
          assists: "498",
          points: "588",
        },
        {
          "player-name": "Zach Parise",
          "player-img": "Wild_Parise_11.png",
          "team-number": 11,
          position: "Left Wing",
          height: "5' 11\"",
          weight: 197,
          "birth-place": "Minneapolis, MN, United States",
          shoots: "Left",
          birthday: "1984-07-28",
          "games-played": 1015,
          goals: "386",
          assists: "406",
          points: "792",
        },
        {
          "player-name": "Cam Talbot",
          "player-img": "Wild_Talbot_Cam.png",
          "team-number": 33,
          position: "Goalie",
          height: "6' 4\"",
          weight: 196,
          "birth-place": "Caledonia, ON, Canada",
          shoots: "Left",
          birthday: "1987-07-05",
          "games-played": 314,
          goals: "",
          assists: "",
          points: "",
        },
        {
          "player-name": "Jared Spurgeon",
          "player-img": "Wild_Spurgeon_Jared.png",
          "team-number": 46,
          position: "Defenseman",
          height: "5' 9\"",
          weight: 167,
          "birth-place": "Edmonton, AB, Canada",
          shoots: "Right",
          birthday: "1989-11-29",
          "games-played": 653,
          goals: "82",
          assists: "192",
          points: "280",
        },
      ],
    },
  },
};
