module.exports = {
  teams: {
    avalanche: {
      "franchise-name": "Avalanche",
      "franchise-location": "Colorado",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Darcy Kuemper",
          "player-img": "Philipp_Grubauer_Colorado_Avalanche.png",
          "team-number": "35",
          position: "Goalie",
          height: "6'5\"",
          weight: "215",
          "birth-place": "Saskatoon, SK, CAN",
          shoots: "Left",
          birthday: "1990-05-05",
          "games-played": "242",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Cale Makar",
          "player-img": "Avalanche_Makar_Cale.png",
          "team-number": "8",
          position: "Defenseman",
          height: "5'11",
          weight: "187",
          "birth-place": "Calgary, AB, CAN",
          shoots: "Right",
          birthday: "1998-10-30",
          "games-played": "101",
          goals: "20",
          assists: "74",
          points: "94",
        },
        {
          "player-name": "Samuel Girard",
          "player-img": "Girard.png",
          "team-number": "49",
          position: "Defenseman",
          height: "5'10\"",
          weight: "170",
          "birth-place": "Roberval, QC, CAN",
          shoots: "Left",
          birthday: "1998-05-12",
          "games-played": "273",
          goals: "17",
          assists: "99",
          points: "116",
        },
        {
          "player-name": "Gabriel Landeskog",
          "player-img": "Avalanche_Landeskog_92.png",
          "team-number": "92",
          position: "Left Wing",
          height: "6'1\"",
          weight: "215",
          "birth-place": "Stockholm, SWE",
          shoots: "Left",
          birthday: "1992-11-23",
          "games-played": "687",
          goals: "218",
          assists: "294",
          points: "512",
        },
        {
          "player-name": "Mikko Rantanen",
          "player-img": "Avalancha-Rantanen-96.png",
          "team-number": "96",
          position: "Right Wing",
          height: "6'4\"",
          weight: "215",
          "birth-place": "Nousiainen, FIN",
          shoots: "Left",
          birthday: "1996-10-29",
          "games-played": "333",
          goals: "129",
          assists: "187",
          points: "316",
        },
        {
          "player-name": "Nathan MacKinnon",
          "player-img": "Avalanche_MacKinnon_29.png",
          "team-number": 29,
          position: "Center",
          height: "6' 0\"",
          weight: 200,
          "birth-place": "Halifax, NS, Canada",
          shoots: "Right",
          birthday: "1995-09-01",
          "games-played": 525,
          goals: "190",
          assists: "305",
          points: "495",
        },
      ],
    },
    blackhawks: {
      "franchise-name": "Blackhawks",
      "franchise-location": "Chicago",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Marc-Andre Fleury",
          "player-img": "Malcolm_Subban_Chicago_Blackhawks.png",
          "team-number": "29",
          position: "Goalie",
          height: "6'2\"",
          weight: "185",
          "birth-place": "Sorel, QC, CAN",
          shoots: "Left",
          birthday: "1984-11-28",
          "games-played": "883",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Seth Jones",
          "player-img": "Brent_Seabrook_Chicago_Blackhawks.png",
          "team-number": "4",
          position: "Defensemen",
          height: "6'4\"",
          weight: "213",
          "birth-place": "Arlington, TX USA",
          shoots: "Right",
          birthday: "1994-10-3",
          "games-played": "580",
          goals: "65",
          assists: "221",
          points: "286",
        },
        {
          "player-name": "Alex DeBrincat",
          "player-img": "Duncan_Keith_Chicago_Blackhawks.png",
          "team-number": "12",
          position: "Left Wing",
          height: "5'7\"",
          weight: "165",
          "birth-place": "Farmington Hills, MI, USA",
          shoots: "Right",
          birthday: "1997-12-18",
          "games-played": "286",
          goals: "119",
          assists: "110",
          points: "229",
        },
        {
          "player-name": "Patrick Kane",
          "player-img": "Blackhawks_Kane_88.png",
          "team-number": "88",
          position: "Right Wing",
          height: "5'10\"",
          weight: "177",
          "birth-place": "Buffalo, NY USA",
          shoots: "Left",
          birthday: "1988-11-19",
          "games-played": "1029",
          goals: "404",
          assists: "684",
          points: "1088",
        },
        {
          "player-name": "Jonathan Toews",
          "player-img": "Blackhawks_Toews_19.png",
          "team-number": 19,
          position: "Center",
          height: "6' 2\"",
          weight: 201,
          "birth-place": "Winnipeg, MB, Canada",
          shoots: "Left",
          birthday: "1988-04-29",
          "games-played": 943,
          goals: "345",
          assists: "470",
          points: "815",
        },
        {
          "player-name": "Kirby Dach",
          "player-img": "Blackhawks_Kirby_Dach.png",
          "team-number": "77",
          position: "Center",
          height: "6'4\"",
          weight: "197",
          "birth-place": "Fort Saskatchewan",
          shoots: "Right",
          birthday: "2001-01-21",
          "games-played": "82",
          goals: "10",
          assists: "23",
          points: "33",
        },
      ],
    },
    bluejackets: {
      "franchise-name": "Blue Jackets",
      "franchise-location": "Columbus",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Sean Kuraly",
          "player-img": "Seth_Jones_Columbus_Blue_Jackets.png",
          "team-number": "7",
          position: "Center",
          height: "6'2\"",
          weight: "213",
          "birth-place": "Dublin, OH, USA",
          shoots: "Left",
          birthday: "1993-01-20",
          "games-played": "270",
          goals: "24",
          assists: "44",
          points: "68",
        },
        {
          "player-name": "Oliver Bjorkstrand",
          "player-img": "Pierre-Luc_Dubois_Columbus_Blue_Jackets.png",
          "team-number": "28",
          position: "Right Wing",
          height: "6'0\"",
          weight: "177",
          "birth-place": "Herning, DNK",
          shoots: "Right",
          birthday: "1995-04-10",
          "games-played": "302",
          goals: "83",
          assists: "94",
          points: "177",
        },
        {
          "player-name": "Boone Jenner",
          "player-img": "BlueJackets_Jenner_38.png",
          "team-number": 38,
          position: "Center",
          height: "6' 2\"",
          weight: 208,
          "birth-place": "Dorchester, ON, Canada",
          shoots: "Left",
          birthday: "1993-06-15",
          "games-played": "530",
          goals: "121",
          assists: "119",
          points: "240",
        },
        {
          "player-name": "Zach Werenski",
          "player-img": "Werenski.png",
          "team-number": 8,
          position: "Defense",
          height: "6' 2\"",
          weight: 214,
          "birth-place": "Grosse Pointe, MI, United States",
          shoots: "Left",
          birthday: "1997-07-19",
          "games-played": "335",
          goals: "65",
          assists: "124",
          points: "189",
        },
        {
          "player-name": "Jakub Voracek",
          "player-img": "Cam_Atkinson_Columbus_Blue_Jackets.png",
          "team-number": "93",
          position: "Right Wing",
          height: "6'2\"",
          weight: "214",
          "birth-place": "Kladno, CZE",
          shoots: "Left",
          birthday: "1989-08-15",
          "games-played": "968",
          goals: "216",
          assists: "522",
          points: "738",
        },
        {
          "player-name": "Gustav Nyquist",
          "player-img": "Blue_Jackets_Nyquist_Gus.png",
          "team-number": 14,
          position: "Center",
          height: "5' 11 \"",
          weight: 179,
          "birth-place": "Halmstad, Sweden",
          shoots: "Left",
          birthday: "1989-09-01",
          "games-played": "570",
          goals: "146",
          assists: "202",
          points: "348",
        },
      ],
    },
    blues: {
      "franchise-name": "Blues",
      "franchise-location": "St. Louis",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Colton Parayko",
          "player-img": "Blues_Parayko_55.png",
          "team-number": 55,
          position: "Defenseman",
          height: "6' 5\"",
          weight: 226,
          "birth-place": "St. Albert, AB, Canada",
          shoots: "Right",
          birthday: "1993-05-12",
          "games-played": "418",
          goals: "41",
          assists: "130",
          points: "171",
        },
        {
          "player-name": "Ryan O'Reilly",
          "player-img": "Blues_OReilly_Ryan.png",
          "team-number": 90,
          position: "Center",
          height: "6' 1\"",
          weight: 216,
          "birth-place": "Clinton, ON, Canada",
          shoots: "Left",
          birthday: "1991-02-07",
          "games-played": "860",
          goals: "219",
          assists: "395",
          points: "614",
        },
        {
          "player-name": "Justin Faulk",
          "player-img": "Jaden_Schwartz_St._Louis_Blues.png",
          "team-number": "72",
          position: "Defenseman",
          height: "6'0\"",
          weight: "217",
          "birth-place": "South St. Paul, MN, USA",
          shoots: "Right",
          birthday: "1992-03-20",
          "games-played": "684",
          goals: "97",
          assists: "202",
          points: "299",
        },
        {
          "player-name": "Torey Krug",
          "player-img": "Blues_Krug_Torey.png",
          "team-number": 47,
          position: "Defenseman",
          height: "5' 9\"",
          weight: 186,
          "birth-place": "Livonia, MI, United States",
          shoots: "Left",
          birthday: "1991-04-12",
          "games-played": "574",
          goals: "69",
          assists: "300",
          points: "369",
        },
        {
          "player-name": "Brayden Schenn",
          "player-img": "Schenn.png",
          "team-number": 10,
          position: "Center",
          height: "6' 1\"",
          weight: 200,
          "birth-place": "Saskatoon, SK, CAN",
          shoots: "Left",
          birthday: "1991-08-22",
          "games-played": "714",
          goals: "195",
          assists: "271",
          points: "466",
        },
        {
          "player-name": "Robert Thomas",
          "player-img": "Blues_Thomas_Robert.png",
          "team-number": 18,
          position: "Center",
          height: "6' 0\"",
          weight: 188,
          "birth-place": "Aurora, ON, Canada",
          shoots: "Right",
          birthday: "1999-07-02",
          "games-played": "169",
          goals: "22",
          assists: "65",
          points: "87",
        },
      ],
    },
    bruins: {
      "franchise-name": "Bruins",
      "franchise-location": "Boston",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Charlie McAvoy",
          "player-img": "Bruins_McAvoy_73.png",
          "team-number": 73,
          position: "Defenseman",
          height: "6' 0\"",
          weight: 208,
          "birth-place": "Long Beach, NY, United States",
          shoots: "Right",
          birthday: "1997-12-21",
          "games-played": 184,
          goals: "19",
          assists: "73",
          points: "92",
        },
        {
          "player-name": "Taylor Hall",
          "player-img": "David_Krejci_Boston_Bruins.png",
          "team-number": 46,
          position: "Center",
          height: "6' 0\"",
          weight: 188,
          "birth-place": "Sternberk, Czech Republic",
          shoots: "Right",
          birthday: "1986-04-28",
          "games-played": "680",
          goals: "228",
          assists: "368",
          points: "596",
        },
        {
          "player-name": "Brandon Carlo",
          "player-img": "Tuukka_Rask_Boston_Bruins.png",
          "team-number": 40,
          position: "Goalie",
          height: "6' 2\"",
          weight: 185,
          "birth-place": "Savonlinna, Finland",
          shoots: "Left",
          birthday: "1987-03-10",
          "games-played": "324",
          goals: "15",
          assists: "40",
          points: "55",
        },
        {
          "player-name": "Brad Marchand",
          "player-img": "Bruins_Marchand_63.png",
          "team-number": 63,
          position: "Left Wing",
          height: "5' 9\"",
          weight: 183,
          "birth-place": "Halifax, NS, Canada",
          shoots: "Left",
          birthday: "1988-05-11",
          "games-played": "804",
          goals: "319",
          assists: "396",
          points: "715",
        },
        {
          "player-name": "Patrice Bergeron",
          "player-img": "Bruins_Bergeron_37.png",
          "team-number": 37,
          position: "Center",
          height: "6' 2\"",
          weight: 194,
          "birth-place": "Ancienne-Lorette, QC, Canada",
          shoots: "Right",
          birthday: "1985-07-24",
          "games-played": "1143",
          goals: "375",
          assists: "542",
          points: "917",
        },
        {
          "player-name": "David Pastrnak",
          "player-img": "Bruins_Pastrnak_88.png",
          "team-number": 88,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 167,
          "birth-place": "Havirov, Czech Republic",
          shoots: "Right",
          birthday: "1996-05-25",
          "games-played": "438",
          goals: "200",
          assists: "227",
          points: "427",
        },
      ],
    },
    canadiens: {
      "franchise-name": "Canadiens",
      "franchise-location": "Montreal",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "Shea Weber",
          "player-img": "Canadiens_Weber_6.png",
          "team-number": 6,
          position: "Defenseman",
          height: "6' 4\"",
          weight: 236,
          "birth-place": "Sicamous, BC, Canada",
          shoots: "Right",
          birthday: "1985-08-14",
          "games-played": 78,
          goals: "20",
          assists: "31",
          points: "51",
        },
        {
          "player-name": "Jeff Petry",
          "player-img": "Petry.png",
          "team-number": 26,
          position: "Defense",
          height: "6' 3\"",
          weight: 204,
          "birth-place": "Ann Arbor, MI, United States",
          shoots: "Right",
          birthday: "1987-12-09",
          "games-played": 80,
          goals: "8",
          assists: "20",
          points: "28",
        },
        {
          "player-name": "Paul Byron",
          "player-img": "PaulByron.png",
          "team-number": 41,
          position: "Left Wing",
          height: "5' 9 \"",
          weight: 162,
          "birth-place": "Ottawa, ON, Canada",
          shoots: "Left",
          birthday: "1989-04-27",
          "games-played": 82,
          goals: "20",
          assists: "15",
          points: "35 ",
        },
        {
          "player-name": "Brendan Gallagher",
          "player-img": "Canadiens_Gallagher_11.png",
          "team-number": 11,
          position: "Right Wing",
          height: "5' 9\"",
          weight: 182,
          "birth-place": "Edmonton, AB, Canada",
          shoots: "Right",
          birthday: "1992-05-06",
          "games-played": 81,
          goals: "24",
          assists: "23",
          points: "47",
        },
        {
          "player-name": "Jonathan Drouin",
          "player-img": "JonathanDrouin.png",
          "team-number": 92,
          position: "Center",
          height: "6' 0 \"",
          weight: 203,
          "birth-place": "Ste-Agathe, QC, Canada",
          shoots: "Left",
          birthday: "1995-03-28",
          "games-played": 77,
          goals: "13",
          assists: "33",
          points: "46 ",
        },
        {
          "player-name": "Carey Price",
          "player-img": "Canadiens_Price_31.png",
          "team-number": 31,
          position: "Goalie",
          height: "6' 3\"",
          weight: 216,
          "birth-place": "Anahim Lake, BC, Canada",
          shoots: "Left",
          birthday: "1987-08-16",
          "games-played": 66,
          goals: "NA",
          assists: "NA",
          points: "",
        },
      ],
    },
    canucks: {
      "franchise-name": "Canucks",
      "franchise-location": "Vancouver",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "J.T. Miller",
          "player-img": "Alex_Edler_Vancouver_Canucks.png",
          "team-number": "9",
          position: "Centerman",
          height: "6'1\"",
          weight: "218 Ib",
          "birth-place": "East Palestine, OH, USA",
          shoots: "Left",
          birthday: "1993-03-14",
          "games-played": "557",
          goals: "137",
          assists: "218",
          points: "355",
        },
        {
          "player-name": "Bo Horvat",
          "player-img": "Canucks_Horvat_53.png",
          "team-number": "53",
          position: "Centerman",
          height: "6'0\"",
          weight: "215 Ib",
          "birth-place": "London, ON, CAN",
          shoots: "Left",
          birthday: "1995-04-05",
          "games-played": "502",
          goals: "139",
          assists: "175",
          points: "314",
        },
        {
          "player-name": "Thatcher Demko",
          "player-img": "Canucks_ThatcherDemko.png",
          "team-number": "35",
          position: "Goalie",
          height: "6'4\"",
          weight: "192 Ib",
          "birth-place": "San Diego, CA, USA",
          shoots: "Left",
          birthday: "1995-08-12",
          "games-played": "72",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Quinn Hughes",
          "player-img": "Canucks_Quinn_Hughes.png",
          "team-number": "43",
          position: "Defencemen",
          height: "5'10\"",
          weight: "180 Ib",
          "birth-place": "Orlando, FL, USA",
          shoots: "Left",
          birthday: "1999-10-14",
          "games-played": "129",
          goals: "11",
          assists: "86",
          points: "97",
        },
        {
          "player-name": "Brock Boeser",
          "player-img": "Canucks_Boeser_Brock.png",
          "team-number": "6",
          position: "Right Wing",
          height: "6'1\"",
          weight: "208 Ib",
          "birth-place": "Burnsville, MN, USA",
          shoots: "Right",
          birthday: "1997-02-25",
          "games-played": "253",
          goals: "98",
          assists: "112",
          points: "210",
        },
        {
          "player-name": "Elias Pettersson",
          "player-img": "Canucks_Pettersson_Elias.png",
          "team-number": "40",
          position: "Centerman",
          height: "6'2\"",
          weight: "176 Ib",
          "birth-place": "Sundsvall, SWE",
          shoots: "Left",
          birthday: "1998-11-1998",
          "games-played": "165",
          goals: "65",
          assists: "88",
          points: "153",
        },
      ],
    },
    capitals: {
      "franchise-name": "Capitals",
      "franchise-location": "Washington",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Nicklas Backstrom",
          "player-img": "Capitals_Backstrom_19.png",
          "team-number": 19,
          position: "Center",
          height: "6' 1\"",
          weight: 208,
          "birth-place": "Gavle, Sweden",
          shoots: "Left",
          birthday: "1987-11-23",
          "games-played": "1011",
          goals: "258",
          assists: "722",
          points: "980",
        },
        {
          "player-name": "TJ Oshie",
          "player-img": "Capitals_Oshie_TJ.png",
          "team-number": 77,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 195,
          "birth-place": "Everett, WA, United States",
          shoots: "Right",
          birthday: "1986-12-23",
          "games-played": "856",
          goals: "260",
          assists: "350",
          points: "610",
        },
        {
          "player-name": "Alex Ovechkin",
          "player-img": "Capitals_Ovechkin_8.png",
          "team-number": 8,
          position: "Left Wing",
          height: "6' 3\"",
          weight: 230,
          "birth-place": "Moscow, Russia",
          shoots: "Right",
          birthday: "1985-09-17",
          "games-played": "1197",
          goals: "730",
          assists: "590",
          points: "1320",
        },
        {
          "player-name": "Michal Kempny",
          "player-img": "Kempny.png",
          "team-number": 6,
          position: "Defense",
          height: "6' 0 \"",
          weight: 194,
          "birth-place": "Hodonin, Czech Republic",
          shoots: "Left",
          birthday: "1990-09-08",
          "games-played": 232,
          goals: "14",
          assists: "47",
          points: "61",
        },
        {
          "player-name": "Tom Wilson",
          "player-img": "Capitals_Wilson_43.png",
          "team-number": 43,
          position: "Right Wing",
          height: "6' 4\"",
          weight: 210,
          "birth-place": "Toronto, ON, Canada",
          shoots: "Right",
          birthday: "1994-03-29",
          "games-played": 522,
          goals: "78",
          assists: "110",
          points: "188",
        },
        {
          "player-name": "John Carlson",
          "player-img": "Capitals_Carlson_74.png",
          "team-number": 74,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 212,
          "birth-place": "Natick, MA, United States",
          shoots: "Right",
          birthday: "1990-01-10",
          "games-played": "809",
          goals: "115",
          assists: "407",
          points: "522",
        },
      ],
    },
    coyotes: {
      "franchise-name": "Coyotes",
      "franchise-location": "Arizona",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Nick Schmaltz",
          "player-img": "Antti_Raanta_Arizona_Coyotes.png",
          "team-number": "40",
          position: "Goalie",
          height: "6'0\"",
          weight: "208",
          "birth-place": "Thunder Bay, ON, CAN",
          shoots: "Left",
          birthday: "1985-12-19",
          "games-played": "232",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Jakob Chychrun",
          "player-img": "Oliver_Ekman-Larsson_Arizona_Coyotes.png",
          "team-number": "6",
          position: "Defenseman",
          height: "6'2\"",
          weight: "210",
          "birth-place": "Boca Raton, FL, USA",
          shoots: "Left",
          birthday: "1998-03-31",
          "games-played": "290",
          goals: "46",
          assists: "75",
          points: "121",
        },
        {
          "player-name": "Niklas Hjalmarsson",
          "player-img": "Hjalmarsson.png",
          "team-number": 4,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 197,
          "birth-place": "Eksjo, Sweden",
          shoots: "Left",
          birthday: "1987-06-06",
          "games-played": 780,
          goals: "25",
          assists: "142",
          points: "167",
        },
        {
          "player-name": "Christian Fischer",
          "player-img": "Christian_Fischer_Arizona_Coyotes.png",
          "team-number": 36,
          position: "Right Wing",
          height: "6' 2 \"",
          weight: 214,
          "birth-place": "Chicago, IL, USA",
          shoots: "Right",
          birthday: "1997-04-15",
          "games-played": "265",
          goals: "38",
          assists: "36",
          points: "74",
        },
        {
          "player-name": "Lawson Crouse",
          "player-img": "Derek_Stepan_Arizona_Coyotes.png",
          "team-number": "67",
          position: "Left Wing",
          height: "6'4\"",
          weight: "220",
          "birth-place": "Mt. Brydges, ON, CAN",
          shoots: "Left",
          birthday: "1997-06-23",
          "games-played": "281",
          goals: "36",
          assists: "40",
          points: "76",
        },
        {
          "player-name": "Clayton Keller",
          "player-img": "Clayton_Keller_Arizona_Coyotes.png",
          "team-number": 9,
          position: "Center",
          height: "5' 10 \"",
          weight: 170,
          "birth-place": "Chesterfield, MO, USA",
          shoots: "Left",
          birthday: "1998-07-29",
          "games-played": "293",
          goals: "68",
          assists: "125",
          points: "193",
        },
      ],
    },
    devils: {
      "franchise-name": "Devils",
      "franchise-location": "New Jersey",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "PK Subban",
          "player-img": "PK_Subban.png",
          "team-number": 76,
          position: "Defenseman",
          height: "6' 0\"",
          weight: 205,
          "birth-place": "Toronto, Ontario, CA",
          shoots: "Right",
          birthday: "1989-05-13",
          "games-played": 68,
          goals: "7",
          assists: "11",
          points: "18",
        },
        {
          "player-name": "Nico Hischier",
          "player-img": "Devils_Hischier_Nico.png",
          "team-number": 13,
          position: "Center",
          height: "6' 1\"",
          weight: 175,
          "birth-place": "Brig, Switzerland",
          shoots: "Left",
          birthday: "1999-01-04",
          "games-played": 209,
          goals: "51",
          assists: "84",
          points: "135",
        },
        {
          "player-name": "Kyle Palmieri",
          "player-img": "Palmieri.png",
          "team-number": 21,
          position: "Right Wing",
          height: "5' 10\"",
          weight: 190,
          "birth-place": "Smithtown, NY",
          shoots: "Left",
          birthday: "1991-02-01",
          "games-played": 561,
          goals: "175",
          assists: "163",
          points: "338",
        },
        {
          "player-name": "Jack Hughes",
          "player-img": "Jack_Hughes.png",
          "team-number": 86,
          position: "Center",
          height: "5' 11\"",
          weight: 170,
          "birth-place": "Orlando, FL, USA",
          birthday: "2001-05-14",
          "games-played": 61,
          goals: "7",
          assists: "14",
          points: "21",
        },
        {
          "player-name": "Travis Zajac",
          "player-img": "Zajac.png",
          "team-number": 19,
          position: "Center",
          height: "6' 2\"",
          weight: 195,
          "birth-place": "Winnipeg, MB, CAN",
          shoots: "Right",
          birthday: "1985-05-13",
          "games-played": 991,
          goals: "195",
          assists: "337",
          points: "532",
        },
        {
          "player-name": "Mackenzie Blackwood",
          "player-img": "Devils_Blackwood_Mackenzie.png",
          "team-number": 29,
          position: "Goalie",
          height: "6' 4\"",
          weight: 225,
          "birth-place": "Thunder Bay, ON, Canada",
          shoots: "Left",
          birthday: "1996-12-06",
          "games-played": 70,
          goals: "64",
          assists: "32",
          points: "24",
        },
      ],
    },
    ducks: {
      "franchise-name": "Ducks",
      "franchise-location": "Anaheim",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Cam Fowler",
          "player-img": "Ducks_Fowler_4.png",
          "team-number": 4,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 211,
          "birth-place": "Windsor, ON, Canada",
          shoots: "Left",
          birthday: "1991-12-05",
          "games-played": "735",
          goals: "72",
          assists: "252",
          points: "324",
        },
        {
          "player-name": "Hampus Lindholm",
          "player-img": "Ducks_Lindholm_47.png",
          "team-number": 47,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 205,
          "birth-place": "Helsingborg, Sweden",
          shoots: "Left",
          birthday: "1994-01-20",
          "games-played": "521",
          goals: "52",
          assists: "148",
          points: "200",
        },
        {
          "player-name": "Rickard Rakell",
          "player-img": "Rakell.png",
          "team-number": 67,
          position: "Left Wing",
          height: "6' 1 \"",
          weight: 202,
          "birth-place": "Sundbyberg, Sweden",
          shoots: "Right",
          birthday: "1993-05-04",
          "games-played": "499",
          goals: "138",
          assists: "173",
          points: "311",
        },
        {
          "player-name": "Jakob Silfverberg",
          "player-img": "Silfverberg.png",
          "team-number": 33,
          position: "Right Wing",
          height: "6' 1 \"",
          weight: 204,
          "birth-place": "Gavle, Sweden",
          shoots: "Right",
          birthday: "1990-10-13",
          "games-played": "605",
          goals: "146",
          assists: "161",
          points: "307",
        },
        {
          "player-name": "John Gibson",
          "player-img": "Ducks_Gibson_36.png",
          "team-number": 36,
          position: "Goalie",
          height: "6' 3\"",
          weight: 227,
          "birth-place": "Pittsburgh, Pennsylvania",
          shoots: "Left",
          birthday: "1993-07-14",
          "games-played": "322",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Ryan Getzlaf",
          "player-img": "Ducks_Getzlaf_15.png",
          "team-number": 15,
          position: "Center",
          height: "6' 4\"",
          weight: 218,
          "birth-place": "Regina, SK, Canada",
          shoots: "Right",
          birthday: "1985-05-10",
          "games-played": "1101",
          goals: "279",
          assists: "703",
          points: "982",
        },
      ],
    },
    flames: {
      "franchise-name": "Flames",
      "franchise-location": "Calgary",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Noah Hanifin",
          "player-img": "Mark_Giordano_Calgary_Flames.png",
          "team-number": "55",
          position: "Defencemen",
          height: "6'3\"",
          weight: "215",
          "birth-place": "Boston, MA, USA",
          shoots: "Left",
          birthday: "1997-01-25",
          "games-played": "436",
          goals: "32",
          assists: "121",
          points: "153",
        },
        {
          "player-name": "Sean Monahan",
          "player-img": "Flames_Monahan_23.png",
          "team-number": "23",
          position: "Center",
          height: "6'2\"",
          weight: "200",
          "birth-place": "Brampton, ON, CAN",
          shoots: "Left",
          birthday: "1994-10-12",
          "games-played": "591",
          goals: "204",
          assists: "235",
          points: "439",
        },
        {
          "player-name": "Mikael Backlund",
          "player-img": "Flames_Backlund_Mikael.png",
          "team-number": 11,
          position: "Center",
          height: "6' 0\"",
          weight: 200,
          "birth-place": "Vasteras, Sweden",
          shoots: "Left",
          birthday: "1989-03-17",
          "games-played": "744",
          goals: "154",
          assists: "243",
          points: "397",
        },
        {
          "player-name": "Johnny Gaudreau",
          "player-img": "Flames_Gaudreau_13.png",
          "team-number": 13,
          position: "Left Wing",
          height: "5' 9\"",
          weight: 150,
          "birth-place": "Salem, NJ, United States",
          shoots: "Left",
          birthday: "1993-08-13",
          "games-played": "520",
          goals: "170",
          assists: "324",
          points: "494",
        },
        {
          "player-name": "Matthew Tkachuk",
          "player-img": "Flames_Tkachuk_Matthew.png",
          "team-number": 19,
          position: "Left Wing",
          height: "6' 2\"",
          weight: 202,
          "birth-place": "Scottsdale, AZ, United States",
          shoots: "Left",
          birthday: "1997-12-11",
          "games-played": "349",
          goals: "110",
          assists: "168",
          points: "278",
        },
        {
          "player-name": "Jacob Markstrom",
          "player-img": "David_Rittich_Calgary_Flames.png",
          "team-number": "25",
          position: "Goalie",
          height: "6'6\"",
          weight: "206",
          "birth-place": "Gävle, SWE",
          shoots: "Left",
          birthday: "1990-01-31",
          "games-played": "315",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
      ],
    },
    flyers: {
      "franchise-name": "Flyers",
      "franchise-location": "Philadelphia",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Jakub Voracek",
          "player-img": "Flyers_Voracek_93.png",
          "team-number": 93,
          position: "Right Wing",
          height: "6' 2\"",
          weight: 214,
          "birth-place": "Kladno, Czech Republic",
          shoots: "Left",
          birthday: "1989-08-15",
          "games-played": 915,
          goals: "207",
          assists: "488",
          points: "695",
        },
        {
          "player-name": "Carter Hart",
          "player-img": "carterhartheadshotEDIT.png",
          "team-number": 79,
          position: "Goalie",
          height: "6' 2 \"",
          weight: 181,
          "birth-place": "Sherwood Park, AB, Canada",
          shoots: "Left",
          birthday: "1998-08-13",
          "games-played": "101",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Claude Giroux",
          "player-img": "Flyers_Giroux_28.png",
          "team-number": 28,
          position: "Center",
          height: "5' 11\"",
          weight: 172,
          "birth-place": "Hearst, ON, Canada",
          shoots: "Right",
          birthday: "1988-01-12",
          "games-played": "943",
          goals: "273",
          assists: "585",
          points: "858",
        },
        {
          "player-name": "Ivan Provorov",
          "player-img": "Provorov.png",
          "team-number": 9,
          position: "Defense",
          height: "6' 1\"",
          weight: 201,
          "birth-place": "Yaroslavl, Russia",
          shoots: "Left",
          birthday: "1997-01-13",
          "games-played": "371",
          goals: "50",
          assists: "109",
          points: "159",
        },
        {
          "player-name": "Kevin Hayes",
          "player-img": "Flyers_Hayes_Kevin.png",
          "team-number": 13,
          position: "Center",
          height: "6' 5\"",
          weight: 216,
          "birth-place": "Dorchester, MA, United States",
          shoots: "Left",
          birthday: "1992-05-08",
          "games-played": "505",
          goals: "127",
          assists: "174",
          points: "301",
        },
        {
          "player-name": "Sean Couturier",
          "player-img": "Courturier.png",
          "team-number": 14,
          position: "Center",
          height: "6' 3\"",
          weight: 211,
          "birth-place": "Phoenix, AZ",
          shoots: "Left",
          birthday: "1992-12-07",
          "games-played": 647,
          goals: "156",
          assists: "246",
          points: "402",
        },
      ],
    },
    hurricanes: {
      "franchise-name": "Hurricanes",
      "franchise-location": "Carolina",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Brett Pesce",
          "player-img": "Brett_Pesce.png",
          "team-number": 22,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 206,
          "birth-place": "Tarrytown, NY, USA",
          shoots: "Right",
          birthday: "1994-11-15",
          "games-played": "405",
          goals: "24",
          assists: "103",
          points: "127",
        },
        {
          "player-name": "Jaccob Slavin",
          "player-img": "Slavin.png",
          "team-number": 74,
          position: "Defense",
          height: "6' 2\"",
          weight: 205,
          "birth-place": "Denver, Colorado",
          shoots: "Left",
          birthday: "1994-05-01",
          "games-played": "429",
          goals: "32",
          assists: "134",
          points: "166",
        },
        {
          "player-name": "Andre Svechnikov",
          "player-img": "Andre_Svechnikov.png",
          "team-number": 37,
          position: "Left Wing",
          height: "6' 2 \"",
          weight: 195,
          "birth-place": "Barnaul, Russia",
          shoots: "Left",
          birthday: "2000-03-26",
          "games-played": 150,
          goals: "44",
          assists: "54",
          points: "98",
        },
        {
          "player-name": "Sebastian Aho",
          "player-img": "SebastianAho.png",
          "team-number": 20,
          position: "Right Wing",
          height: "5' 11 \"",
          weight: 172,
          "birth-place": "Rauma, Finland",
          shoots: "Left",
          birthday: "1997-07-26",
          "games-played": "366",
          goals: "145",
          assists: "175",
          points: "320",
        },
        {
          "player-name": "Jordan Staal",
          "player-img": "Hurricanes_Staal_11.png",
          "team-number": 11,
          position: "Center",
          height: "6' 4\"",
          weight: 220,
          "birth-place": "Thunder Bay, ON, Canada",
          shoots: "Left",
          birthday: "1988-09-10",
          "games-played": "1014",
          goals: "241",
          assists: "334",
          points: "575",
        },
        {
          "player-name": "Teuvo Teravainen",
          "player-img": "Teuvo.png",
          "team-number": 86,
          position: "Left Wing",
          height: "5' 11 \"",
          weight: 178,
          "birth-place": "Helsinki, Finland",
          shoots: "Left",
          birthday: "1994-09-11",
          "games-played": 428,
          goals: "91",
          assists: "198",
          points: "289",
        },
      ],
    },
    islanders: {
      "franchise-name": "Islanders",
      "franchise-location": "New York",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Cal Clutterbuck",
          "player-img": "Nick_Leddy_New_York_Islanders.png",
          "team-number": "15",
          position: "Right Wing",
          height: "6'0\"",
          weight: "212",
          "birth-place": "Welland, ON, CAN",
          shoots: "Right",
          birthday: "1987-11-18",
          "games-played": "874",
          goals: "124",
          assists: "123",
          points: "247",
        },
        {
          "player-name": "Anders Lee",
          "player-img": "Islanders_Lee.png",
          "team-number": 27,
          position: "Left Wing",
          height: "6' 3 \"",
          weight: 231,
          "birth-place": "Edina, MN, United States",
          shoots: "Left",
          birthday: "1990-07-03",
          "games-played": "520",
          goals: "184",
          assists: "136",
          points: "320",
        },
        {
          "player-name": "Josh Bailey",
          "player-img": "Islanders_Bailey.png",
          "team-number": 12,
          position: "Right Wing",
          height: "6' 1\"",
          weight: 200,
          "birth-place": "Bowmanville, ON, Canada",
          shoots: "Left",
          birthday: "1989-10-02",
          "games-played": "919",
          goals: "162",
          assists: "349",
          points: "511",
        },
        {
          "player-name": "JG Pageau",
          "player-img": "Islanders_PageauHeadshot.png",
          "team-number": 44,
          position: "Center",
          height: "5' 10 \"",
          weight: 180,
          "birth-place": "Ottawa, ON, Canada",
          shoots: "Right",
          birthday: "1992-11-11",
          "games-played": "489",
          goals: "103",
          assists: "109",
          points: "212",
        },
        {
          "player-name": "Brock Nelson",
          "player-img": "Islanders_Nelson.png",
          "team-number": 29,
          position: "Center",
          height: "6' 3\"",
          weight: 212,
          "birth-place": "Warroad, MN, United States",
          shoots: "Left",
          birthday: "1991-10-15",
          "games-played": "604",
          goals: "168",
          assists: "160",
          points: "328",
        },
        {
          "player-name": "Mathew Barzal",
          "player-img": "Islanders_Barzal.png",
          "team-number": 13,
          position: "Center",
          height: "6' 0 \"",
          weight: 187,
          "birth-place": "Coquitlam, BC, Canada",
          shoots: "Right",
          birthday: "1997-05-26",
          "games-played": "289",
          goals: "76",
          assists: "176",
          points: "252",
        },
      ],
    },
    jets: {
      "franchise-name": "Jets",
      "franchise-location": "Winnipeg",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "Blake Wheeler",
          "player-img": "Jets_Wheeler_26.png",
          "team-number": 26,
          position: "Right Wing",
          height: "6' 5\"",
          weight: 225,
          "birth-place": "Plymouth, MN, United States",
          shoots: "Right",
          birthday: "1986-08-31",
          "games-played": "981",
          goals: "279",
          assists: "528",
          points: "807",
        },
        {
          "player-name": "Nikolaj Ehlers",
          "player-img": "Patrik_Laine_Winnipeg_Jets.png",
          "team-number": "27",
          position: "Left Wing",
          height: "6'0\"",
          weight: "172 Ib",
          "birth-place": "Aalborg, DNK",
          shoots: "Left",
          birthday: "1996-02-14",
          "games-played": "416",
          goals: "136",
          assists: "167",
          points: "303",
        },
        {
          "player-name": "Adam Lowry",
          "player-img": "Jets_Lowry_17.png",
          "team-number": "17",
          position: "Centerman",
          height: "6'5\"",
          weight: "210 Ib",
          "birth-place": "St. Louis, MO USA",
          shoots: "Left",
          birthday: "1993-03-29",
          "games-played": "460",
          goals: "67",
          assists: "80",
          points: "147",
        },
        {
          "player-name": "Josh Morrissey",
          "player-img": "Josh_Morrissey.png",
          "team-number": "44",
          position: "Defencemen",
          height: "6'0\"",
          weight: "195 Ib",
          "birth-place": "Calgary, AB, CAN",
          shoots: "Left",
          birthday: "1995-03-28",
          "games-played": "344",
          goals: "28",
          assists: "101",
          points: "129",
        },
        {
          "player-name": "Mark Scheifele",
          "player-img": "Jets_Scheifele_55.png",
          "team-number": "55",
          position: "Centerman",
          height: "6'3\"",
          weight: "207 Ib",
          "birth-place": "Kitchener, ON, CAN",
          shoots: "Right",
          birthday: "1993-03-15",
          "games-played": "575",
          goals: "201",
          assists: "306",
          points: "507",
        },
        {
          "player-name": "Connor Hellebuyck",
          "player-img": "ConnorHellebuyck.png",
          "team-number": 37,
          position: "Goalie",
          height: "6' 4 \"",
          weight: 207,
          "birth-place": "Commerce, MI, USA",
          shoots: "Left",
          birthday: "1993-05-19",
          "games-played": "315",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
      ],
    },
    kings: {
      "franchise-name": "Kings",
      "franchise-location": "Los Angeles",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Drew Doughty",
          "player-img": "Kings_Doughty_8.png",
          "team-number": 8,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 213,
          "birth-place": "London, ON, Canada",
          shoots: "Right",
          birthday: "1989-12-08",
          "games-played": "975",
          goals: "125",
          assists: "411",
          points: "536",
        },
        {
          "player-name": "Alex Iafallo",
          "player-img": "AlexIafallo.png",
          "team-number": 19,
          position: "Left Wing",
          height: "6' 0 \"",
          weight: 188,
          "birth-place": "Eden, NY, USA",
          shoots: "Left",
          birthday: "1993-12-21",
          "games-played": 227,
          goals: "41",
          assists: "60",
          points: "101",
        },
        {
          "player-name": "Adrian Kempe",
          "player-img": "Kempe.png",
          "team-number": 9,
          position: "Center",
          height: "6' 2 \"",
          weight: 201,
          "birth-place": "Kramfors, Sweden",
          shoots: "Left",
          birthday: "1996-09-13",
          "games-played": "312",
          goals: "55",
          assists: "77",
          points: "132",
        },
        {
          "player-name": "Dustin Brown",
          "player-img": "Kings_Brown_23.png",
          "team-number": 23,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 207,
          "birth-place": "Ithaca, NY, United States",
          shoots: "Right",
          birthday: "1984-11-04",
          "games-played": "1,232",
          goals: "316",
          assists: "368",
          points: "684",
        },
        {
          "player-name": "Anze Kopitar",
          "player-img": "Kings_Kopitar_11.png",
          "team-number": 11,
          position: "Center",
          height: "6' 3\"",
          weight: 224,
          "birth-place": "Jesenice, Slovenia",
          shoots: "Left",
          birthday: "1987-08-24",
          "games-played": "1,129",
          goals: "346",
          assists: "654",
          points: "1,000",
        },
        {
          "player-name": "Calvin Petersen",
          "player-img": "Jonathan_Quick_Los_Angeles_Kings.png",
          "team-number": "40",
          position: "Goalie",
          height: "6'1\"",
          weight: "185",
          "birth-place": "Waterloo, IA, USA",
          shoots: "Right",
          birthday: "1994-10-19",
          "games-played": "54",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
      ],
    },
    knights: {
      "franchise-name": "Golden Knights",
      "franchise-location": "Vegas",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Max Pacioretty",
          "player-img": "Marc-Andre_Fleury_Vegas_Golden_Knights.png",
          "team-number": "67",
          position: "Left Wing",
          height: "6'2\"",
          weight: "215",
          "birth-place": "New Canaan, CT, USA",
          shoots: "Left",
          birthday: "1988-11-20",
          "games-played": "811",
          goals: "304",
          assists: "301",
          points: "605",
        },
        {
          "player-name": "Shea Theodore",
          "player-img": "VGK_Theodore_Shea.png",
          "team-number": 27,
          position: "Defensemen",
          height: "6' 2 \"",
          weight: 195,
          "birth-place": "Langley, BC, Canada",
          shoots: "Left",
          birthday: " 1995-08-03",
          "games-played": "317",
          goals: "44",
          assists: "127",
          points: "171",
        },
        {
          "player-name": "Reilly Smith",
          "player-img": "Smith.png",
          "team-number": 19,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 185,
          "birth-place": "Toronto, ON, Canada",
          shoots: "Left",
          birthday: "1991-04-01",
          "games-played": "630",
          goals: "158",
          assists: "221",
          points: "379",
        },
        {
          "player-name": "Mark Stone",
          "player-img": "MarkStone.png",
          "team-number": 61,
          position: "Right Wing",
          height: "6' 4 \"",
          weight: 219,
          "birth-place": "Winnipeg, MB, Canada",
          shoots: "Right",
          birthday: "1992-05-13",
          "games-played": "504",
          goals: "170",
          assists: "276",
          points: "446",
        },
        {
          "player-name": "Jonathan Marchessault",
          "player-img": "Marchessault.png",
          "team-number": 81,
          position: "Center",
          height: "5' 9\"",
          weight: 174,
          "birth-place": "Cap-Rouge, QC, CAN",
          shoots: "Right",
          birthday: "1990-12-27",
          "games-played": "404",
          goals: "130",
          assists: "165",
          points: "295",
        },
        {
          "player-name": "Brayden McNabb",
          "player-img": "McNabb.png",
          "team-number": 3,
          position: "Defense",
          height: "6' 4\"",
          weight: 216,
          "birth-place": "Davidson, SASK",
          shoots: "Left",
          birthday: "1986-01-21",
          "games-played": "507",
          goals: "20",
          assists: "78",
          points: "98",
        },
      ],
    },
    lightning: {
      "franchise-name": "Lightning",
      "franchise-location": "Tampa Bay",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Andrei Vasilevskiy",
          "player-img": "Lightning_Vasilevskiy_88.png",
          "team-number": 88,
          position: "Goalie",
          height: "6' 3\"",
          weight: 207,
          "birth-place": "Tyumen, Russia",
          shoots: "Left",
          birthday: "1994-07-25",
          "games-played": 230,
          goals: "159",
          assists: "73",
          points: "18",
        },
        {
          "player-name": "Victor Hedman",
          "player-img": "Lightning_Hedman_77.png",
          "team-number": 77,
          position: "Defenseman",
          height: "6' 6\"",
          weight: 230,
          "birth-place": "Ornskoldsvik, Sweden",
          shoots: "Left",
          birthday: "1990-12-18",
          "games-played": 762,
          goals: "105",
          assists: "368",
          points: "473",
        },
        {
          "player-name": "Ryan McDonagh",
          "player-img": "McDonagh.png",
          "team-number": 27,
          position: "Defense",
          height: "6' 1 \"",
          weight: 215,
          "birth-place": "St. Paul, MN, USA",
          shoots: "Left",
          birthday: "1989-06-13",
          "games-played": "712",
          goals: "67",
          assists: "244",
          points: "311",
        },
        {
          "player-name": "Brayden Point",
          "player-img": "Bay_Point_Brayden.png",
          "team-number": 21,
          position: "Center",
          height: "5' 10\"",
          weight: 166,
          "birth-place": "Calgary, AB, Canada",
          shoots: "Right",
          birthday: "1996-03-13",
          "games-played": "351",
          goals: "139",
          assists: "171",
          points: "310",
        },
        {
          "player-name": "Steven Stamkos",
          "player-img": "Lightning_Stamkos_91.png",
          "team-number": 91,
          position: "Center",
          height: "6' 1\"",
          weight: 194,
          "birth-place": "Markham, ON, Canada",
          shoots: "Right",
          birthday: "1990-02-07",
          "games-played": 803,
          goals: "422",
          assists: "410",
          points: "832",
        },
        {
          "player-name": "Nikita Kucherov",
          "player-img": "Bay_Kucherov_Nikita.png",
          "team-number": 86,
          position: "Right Wing",
          height: "5' 11\"",
          weight: 183,
          "birth-place": "Maykop, Russia",
          shoots: "Left",
          birthday: "1993-06-17",
          "games-played": "515",
          goals: "221",
          assists: "326",
          points: "547",
        },
      ],
    },
    mapleleafs: {
      "franchise-name": "Maple Leafs",
      "franchise-location": "Toronto",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "Morgan Rielly",
          "player-img": "MapleLeafs_Rielly_44.png",
          "team-number": "44",
          position: "Defencemen",
          height: "6'1\"",
          weight: "219 lb",
          "birth-place": "Vancouver, BC, CAN",
          shoots: "Left",
          birthday: "1994-03-09",
          "games-played": "572",
          goals: "59",
          assists: "246",
          points: "305",
        },
        {
          "player-name": "Justin Holl",
          "player-img": "Leafs_Justin_Holl_2020.png",
          "team-number": "3",
          position: "Defencemen",
          height: "6'4\"",
          weight: "210 lb",
          "birth-place": "Tonka Bay, MN, USA",
          shoots: "Right",
          birthday: "1991-01-30",
          "games-played": "136",
          goals: "6",
          assists: "35",
          points: "41",
        },
        {
          "player-name": "Frederik Andersen",
          "player-img": "MapleLeafs_Andersen_31.png",
          "team-number": 31,
          position: "Goalie",
          height: "6' 4\"",
          weight: 220,
          "birth-place": "Heming, Denmark",
          shoots: "Left",
          birthday: "1989-10-02",
          "games-played": 369,
          goals: "NA",
          assists: "NA",
          points: "NA",
        },
        {
          "player-name": "Jack Campell",
          "player-img": "Hyman.png",
          "team-number": "36",
          position: "Goalie",
          height: "6'4\"",
          weight: "197 lb",
          "birth-place": "Port Huron, MI, USA",
          shoots: "Left",
          birthday: "1992-01-09",
          "games-played": "86",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "John Tavares",
          "player-img": "TavaresLeafs.png",
          "team-number": "91",
          position: "Centerman",
          height: "6'1\"",
          weight: "215 lb",
          "birth-place": "Mississauga, ON, CAN",
          shoots: "Left",
          birthday: "1990-09-20",
          "games-played": "870",
          goals: "364",
          assists: "455",
          points: "819",
        },
        {
          "player-name": "Auston Matthews",
          "player-img": "MapleLeafs-Matthews-34.png",
          "team-number": "34",
          position: "Centerman",
          height: "6'3\"",
          weight: "220 lb",
          "birth-place": "San Ramon, CA, USA",
          shoots: "Left",
          birthday: "1997-09-17",
          "games-played": "334",
          goals: "199",
          assists: "152",
          points: "351",
        },
      ],
    },
    oilers: {
      "franchise-name": "Oilers",
      "franchise-location": "Edmonton",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "Kailer Yamamoto",
          "player-img": "James_Neal_Edmonton_Oilers.png",
          "team-number": "56",
          position: "Right Wing",
          height: "5'8\"",
          weight: "152 Ib",
          "birth-place": "Spokane, WA",
          shoots: "Right",
          birthday: "1998-09-29",
          "games-played": "105",
          goals: "20",
          assists: "32",
          points: "52",
        },
        {
          "player-name": "Connor McDavid",
          "player-img": "Oilers_McDavid_97.png",
          "team-number": 97,
          position: "Center",
          height: "6' 1\"",
          weight: 190,
          "birth-place": "Richmond Hill, ON, Canada",
          shoots: "Left",
          birthday: "1997-01-13",
          "games-played": "407",
          goals: "195",
          assists: "379",
          points: "574",
        },
        {
          "player-name": "Leon Draisaitl",
          "player-img": "Leon.png",
          "team-number": 29,
          position: "Right Wing",
          height: "6' 1\"",
          weight: 214,
          "birth-place": "Cologne, Germany",
          shoots: "Left",
          birthday: "1995-10-27",
          "games-played": "478",
          goals: "199",
          assists: "307",
          points: "506",
        },
        {
          "player-name": "Jess Puljujarvi",
          "player-img": "Oscar_Klefbom_Edmonton_Oilers.png",
          "team-number": "13",
          position: "Right Wing",
          height: "6'4\"",
          weight: "201 Ib",
          "birth-place": "Alvkarleby, SWE",
          shoots: "Right",
          birthday: "1998-05-07",
          "games-played": "194",
          goals: "32",
          assists: "30",
          points: "62",
        },
        {
          "player-name": "Ryan Nugent-Hopkins",
          "player-img": "Adam_Larsson_Edmonton_Oilers.png",
          "team-number": "93",
          position: "Left Wing",
          height: "6'0\"",
          weight: "184 Ib",
          "birth-place": "Burnaby, BC, CAN",
          shoots: "Left",
          birthday: "1993-04-12",
          "games-played": "656",
          goals: "185",
          assists: "293",
          points: "478",
        },
        {
          "player-name": "Darnell Nurse",
          "player-img": "Mikko_Koskinen_Edmonton_Oilers.png",
          "team-number": "25",
          position: "Defenceman",
          height: "6'4\"",
          weight: "221 Ib",
          "birth-place": "Hamilton, ON, CAN",
          shoots: "Left",
          birthday: "1995-02-04",
          "games-played": "406",
          goals: "45",
          assists: "112",
          points: "157",
        },
      ],
    },
    panthers: {
      "franchise-name": "Panthers",
      "franchise-location": "Florida",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Aaron Ekblad",
          "player-img": "Panthers_Ekblad_5.png",
          "team-number": 5,
          position: "Defenseman",
          height: "6' 4\"",
          weight: 216,
          "birth-place": "Windsor, ON, Canada",
          shoots: "Right",
          birthday: "1996-02-07",
          "games-played": 458,
          goals: "71",
          assists: "141",
          points: "212",
        },
        {
          "player-name": "MacKenzie Weegar",
          "player-img": "Keith_Yandle_Florida_Panthers.png",
          "team-number": "52",
          position: "Defenseman",
          height: "6'0",
          weight: "200 lb",
          "birth-place": "Ottawa, ON",
          shoots: "Right",
          birthday: "1994-07-01",
          "games-played": "296",
          goals: "19",
          assists: "58",
          points: "77",
        },
        {
          "player-name": "Jonathan Huberdeau",
          "player-img": "Panthers_Huberdeau_11.png",
          "team-number": 11,
          position: "Left Wing",
          height: "6' 1\"",
          weight: 188,
          "birth-place": "Saint-Jerome, QC, Canada",
          shoots: "Left",
          birthday: "1993-06-04",
          "games-played": "591",
          goals: "168",
          assists: "330",
          points: "498",
        },
        {
          "player-name": "Sergei Bobrovsky",
          "player-img": "Sergei_Bobrovsky.png",
          "team-number": 72,
          position: "Goalie",
          height: "6' 2\"",
          weight: 187,
          "birth-place": "Novokuznetsk, Russia",
          shoots: "Left",
          birthday: "1988-09-20",
          "games-played": "538",
          goals: "524",
          assists: "297",
          points: "180",
        },
        {
          "player-name": "Aleksander Barkov",
          "player-img": "Panthers_Barkov_16.png",
          "team-number": 16,
          position: "Center",
          height: "6' 3\"",
          weight: 213,
          "birth-place": "Tampere, Finland",
          shoots: "Left",
          birthday: "1995-09-02",
          "games-played": 479,
          goals: "155",
          assists: "252",
          points: "407",
        },
        {
          "player-name": "Patric Hornqvist",
          "player-img": "Panthers_Hornqvist.png",
          "team-number": 70,
          position: "Right Wing",
          height: "5' 11 \"",
          weight: 189,
          "birth-place": "Sollentuna, Sweden",
          shoots: "Right",
          birthday: "1987-01-01",
          "games-played": "814",
          goals: "252",
          assists: "260",
          points: "512",
        },
      ],
    },
    penguins: {
      "franchise-name": "Penguins",
      "franchise-location": "Pittsburgh",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Evgeni Malkin",
          "player-img": "Penguins_Malkin_Evgeni_02.png",
          "team-number": 71,
          position: "Center",
          height: "6' 3\"",
          weight: 195,
          "birth-place": "Magnitogorsk, Russia",
          shoots: "Left",
          birthday: "1986-07-31",
          "games-played": 907,
          goals: "416",
          assists: "660",
          points: "1076",
        },
        {
          "player-name": "Kris Letang",
          "player-img": "Penguins_Letang_Kris_02.png",
          "team-number": 58,
          position: "Defenseman",
          height: "6' 0\"",
          weight: 201,
          "birth-place": "Montreal, QC, Canada",
          shoots: "Right",
          birthday: "1987-04-24",
          "games-played": "863",
          goals: "134",
          assists: "448",
          points: "582",
        },
        {
          "player-name": "Jake Guentzel",
          "player-img": "Penguins_Guentzel_Jake_02.png",
          "team-number": 59,
          position: "Left Wing",
          height: "5' 11 \"",
          weight: 180,
          "birth-place": "Omaha, NE, USA",
          shoots: "Left",
          birthday: "1994-10-06",
          "games-played": "299",
          goals: "121",
          assists: "136",
          points: "257",
        },
        {
          "player-name": "Brian Dumoulin",
          "player-img": "Penguins_Dumoulin_Brian_03.png",
          "team-number": 8,
          position: "Defense",
          height: "6' 4 \"",
          weight: 207,
          "birth-place": "Biddeford, ME, USA",
          shoots: "Left",
          birthday: "1991-09-06",
          "games-played": "388",
          goals: "15",
          assists: "81",
          points: "96",
        },
        {
          "player-name": "Sidney Crosby",
          "player-img": "Penguins_Crosby_Sidney_01.png",
          "team-number": 87,
          position: "Center",
          height: "5' 11\"",
          weight: 200,
          "birth-place": "Cole Harbour, NS, Canada",
          shoots: "Left",
          birthday: "1987-08-07",
          "games-played": "1039",
          goals: "486",
          assists: "839",
          points: "183",
        },
        {
          "player-name": "Tristan Jarry",
          "player-img": "Penguins_Jarry_Tristan_03.png",
          "team-number": 35,
          position: "Goalie",
          height: "6' 2\"",
          weight: 194,
          "birth-place": "Surrey, BC, Canada",
          shoots: "Left",
          birthday: "1995-03-29",
          "games-played": "101",
          goals: "0",
          assists: "0",
          points: "0",
        },
      ],
    },
    predators: {
      "franchise-name": "Predators",
      "franchise-location": "Nashville",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Matt Duchene",
          "player-img": "Matt_Duchene_Nashville_Predators.png",
          "team-number": 95,
          position: "Center",
          height: "5' 11 \"",
          weight: 195,
          "birth-place": "Haliburton, ON, Canada",
          shoots: "Left",
          birthday: "1991-01-16",
          "games-played": "827",
          goals: "251",
          assists: "351",
          points: "602",
        },
        {
          "player-name": "Roman Josi",
          "player-img": "Roman_Josi_Nashville_Predators.png",
          "team-number": 59,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 192,
          "birth-place": "Bern, Switzerland",
          shoots: "Left",
          birthday: "1990-06-01",
          "games-played": "680",
          goals: "117",
          assists: "329",
          points: "446",
        },
        {
          "player-name": "Juuse Saros",
          "player-img": "Ryan_Ellis_Nashville_Predators.png",
          "team-number": "74",
          position: "Goalie",
          height: "5'11\"",
          weight: "180",
          "birth-place": "Forssa, FIN",
          shoots: "Left",
          birthday: "1995-04-19",
          "games-played": "155",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Mikael Granlund",
          "player-img": "Filip_Forsberg_Nashville_Predators.png",
          "team-number": "64",
          position: "Center",
          height: "5'10\"",
          weight: "185",
          "birth-place": "Oulu, FIN",
          shoots: "Left",
          birthday: "1992-002-26",
          "games-played": "591",
          goals: "124",
          assists: "255",
          points: "379",
        },
        {
          "player-name": "Ryan Johansen",
          "player-img": "Pekka_Rinne_Nashville_Predators.png",
          "team-number": "92",
          position: "Center",
          height: "6'3\"",
          weight: "218",
          "birth-place": "Vancouver, BC, CAN",
          shoots: "Right",
          birthday: "1992-07-31",
          "games-played": "708",
          goals: "151",
          assists: "313",
          points: "464",
        },
        {
          "player-name": "Mattias Ekholm",
          "player-img": "Mattias_Ekholm_Nashville_Predators.png",
          "team-number": 14,
          position: "Defense",
          height: "6' 4\"",
          weight: 215,
          "birth-place": "Borlange, Sweden",
          shoots: "Left",
          birthday: "1990-05-24",
          "games-played": "586",
          goals: "51",
          assists: "168",
          points: "219",
        },
      ],
    },
    czech: {
      "franchise-name": "Czech",
      "franchise-location": "Czech Republic",
      country: "CZ",
      locale: "en-US",
      players: [
        {
          "player-name": "David Rittich",
          "player-img": "2.png",
          "team-number": 33,
          position: "Goalie",
          height: "6' 3\"",
          weight: 206,
          "birth-place": "Jihlava, Czech Republic",
          shoots: "Left",
          birthday: "1992-08-19",
          "games-played": 115,
          goals: "106",
          assists: "",
          points: "",
        },
        {
          "player-name": "David Pastrnak",
          "player-img": "1.png",
          "team-number": 88,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 194,
          "birth-place": "Havirov, Czech Republic",
          shoots: "Right",
          birthday: "1996-05-25",
          "games-played": 390,
          goals: "180",
          assists: "190",
          points: "379",
        },
        {
          "player-name": "Dominik Kubalik",
          "player-img": "3.png",
          "team-number": 8,
          position: "Left Wing",
          height: "6' 2\"",
          weight: 179,
          "birth-place": "Plzen, Czech Republic",
          shoots: "Left",
          birthday: "1995-08-21",
          "games-played": 68,
          goals: "30",
          assists: "16",
          points: "46",
        },
        {
          "player-name": "Jakub Voracek",
          "player-img": "4.png",
          "team-number": 93,
          position: "Right Wing",
          height: "6' 2\"",
          weight: 214,
          "birth-place": "Kladno, Czech Republic",
          shoots: "Left",
          birthday: "1989-08-15",
          "games-played": 907,
          goals: "215",
          assists: "488",
          points: "695",
        },
        {
          "player-name": "Ondrej Palat",
          "player-img": "5.png",
          "team-number": 18,
          position: "Left Wing",
          height: "6' 0\"",
          weight: 194,
          "birth-place": "Frydek-Mistek, Czech Republic",
          shoots: "Left",
          birthday: "1991-03-28",
          "games-played": 496,
          goals: "110",
          assists: "218",
          points: "328",
        },
        {
          "player-name": "Tomas Hertl ",
          "player-img": "6.png",
          "team-number": 48,
          position: "Center",
          height: "6' 2\"",
          weight: 215,
          "birth-place": "FPraha, Czech Republic",
          shoots: "Left",
          birthday: "1993-11-12",
          "games-played": 453,
          goals: "132",
          assists: "148",
          points: "280",
        },
      ],
    },
    rangers: {
      "franchise-name": "Rangers",
      "franchise-location": "New York",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Igor Shesterkin",
          "player-img": "NY_Rangers_Shestyorkin_Igor.png",
          "team-number": 31,
          position: "Goalie",
          height: "6' 2\"",
          weight: 182,
          "birth-place": "Moscow, Russia",
          shoots: "Left",
          birthday: "1995-12-30",
          "games-played": "47",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Alexis Lafrenière",
          "player-img": "Kaapo_Kakko_New_York_Rangers.png",
          "team-number": "13",
          position: "Left Wing",
          height: "6'2\"",
          weight: "196",
          "birth-place": "St-Eustache, QC, CAN",
          shoots: "Left",
          birthday: "2001-10-11",
          "games-played": "56",
          goals: "12",
          assists: "9",
          points: "21",
        },
        {
          "player-name": "Adam Fox",
          "player-img": "NY_Rangers_Fox_Adam.png",
          "team-number": 23,
          position: "Defensemen",
          height: "5' 11\"",
          weight: 181,
          "birth-place": "Jericho, NY, United States",
          shoots: "Right",
          birthday: "1998-12-17",
          "games-played": "125",
          goals: "13",
          assists: "76",
          points: "89",
        },
        {
          "player-name": "Chris Krider",
          "player-img": "NY_Rangers_Kreider_Chris.png",
          "team-number": 20,
          position: "Left Wing",
          height: "6' 3\"",
          weight: 217,
          "birth-place": "Boxford, MA, United States",
          shoots: "Left",
          birthday: "1991-04-30",
          "games-played": 523,
          goals: "157",
          assists: "159",
          points: "316",
        },
        {
          "player-name": "Artemi Panarin",
          "player-img": "NY_Rangers_Panarin_Artemi.png",
          "team-number": 10,
          position: "Left Wing",
          height: "5' 11\"",
          weight: 170,
          "birth-place": "Korkino, Russia",
          shoots: "Right",
          birthday: "1991-10-30",
          "games-played": "433",
          goals: "165",
          assists: "308",
          points: "473",
        },
        {
          "player-name": "Mika Zibanejad",
          "player-img": "NY_Rangers_Zibanejad_Mika.png",
          "team-number": 93,
          position: "Center",
          height: "6' 2\"",
          weight: 208,
          "birth-place": "Huddinge, Sweden",
          shoots: "Right",
          birthday: "1993-04-18",
          "games-played": 548,
          goals: "176",
          assists: "208",
          points: "384",
        },
      ],
    },
    redwings: {
      "franchise-name": "Red Wings",
      "franchise-location": "Detroit",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Alex Nedeljkovic",
          "player-img": "Jonathan_Bernier_Detroit_Red_Wings.png",
          "team-number": "39",
          position: "Goalie",
          height: "6'0\"",
          weight: "203",
          "birth-place": "Parma, OH, USA",
          shoots: "Left",
          birthday: "1996-01-07",
          "games-played": "29",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Dylan Larkin",
          "player-img": "RedWings_Larkin_71.png",
          "team-number": 71,
          position: "Center",
          height: "6'1\"",
          weight: 190,
          "birth-place": "Waterford, Michigan",
          shoots: "Left",
          birthday: "1996-07-30",
          "games-played": "433",
          goals: "116",
          assists: "173",
          points: "289",
        },
        {
          "player-name": "Filip Hronek",
          "player-img": "Red_Wings_Hronek_Filip.png",
          "team-number": 17,
          position: "Defenseman",
          height: "6'0\"",
          weight: 183,
          "birth-place": "Hradec Králové, Czech Republic",
          shoots: "Right",
          birthday: "1997-11-02",
          "games-played": "167",
          goals: "16",
          assists: "64",
          points: "80",
        },
        {
          "player-name": "Frans Nielsen",
          "player-img": "Frans_Nielsen.png",
          "team-number": 81,
          position: "Center",
          height: "6'1\"",
          weight: 186,
          "birth-place": "Herning, Denmark",
          shoots: "Left",
          birthday: "1984-04-24",
          "games-played": 896,
          goals: "166",
          assists: "301",
          points: "467",
        },
        {
          "player-name": "Tyler Bertuzzi",
          "player-img": "Tyler_Bertuzzi.png",
          "team-number": 59,
          position: "Left Wing",
          height: "6'1\"",
          weight: 199,
          "birth-place": "Sudbury, ON, Canada",
          shoots: "Left",
          birthday: "1995-02-24",
          "games-played": "208",
          goals: "54",
          assists: "72",
          points: "126",
        },
        {
          "player-name": "Mark Staal",
          "player-img": "Luke_Glendening_Detroit_Red_Wings.png",
          "team-number": "18",
          position: "Defenseman",
          height: "6'4\"",
          weight: "208",
          "birth-place": "Thunder Bay, ON, CAN",
          shoots: "Left",
          birthday: "1987-01-13",
          "games-played": "948",
          goals: "46",
          assists: "152",
          points: "198",
        },
      ],
    },
    sabres: {
      "franchise-name": "Sabres",
      "franchise-location": "Buffalo",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Victor Olofsson",
          "player-img": "Sam_Reinhart_Buffalo_Sabres.png",
          "team-number": "71",
          position: "Left Wing",
          height: "5'11\"",
          weight: "182",
          "birth-place": "Ornskoldsvik, SWE",
          shoots: "Left",
          birthday: "1995-07-18",
          "games-played": "116",
          goals: "35",
          assists: "43",
          points: "78",
        },
        {
          "player-name": "Zemgus Girgensons",
          "player-img": "Jake_McCabe_Buffalo_Sabres.png",
          "team-number": "28",
          position: "Left Wing",
          height: "6'2\"",
          weight: "213",
          "birth-place": "Riga, LVA",
          shoots: "Left",
          birthday: "1994-01-05",
          "games-played": "489",
          goals: "61",
          assists: "77",
          points: "138",
        },
        {
          "player-name": "Rasmus Dahlin",
          "player-img": "Rasmus_Dahlin_Buffalo_Sabres.png",
          "team-number": 26,
          position: "Defenseman",
          height: "6' 3\"",
          weight: 190,
          "birth-place": "Lidkoping, Sweden",
          shoots: "Left",
          birthday: "2000-04-13",
          "games-played": "197",
          goals: "18",
          assists: "89",
          points: "107",
        },
        {
          "player-name": "Kyle Okposo",
          "player-img": "Kyle_Okposo_Buffalo_Sabres.png",
          "team-number": 21,
          position: "Right Wing",
          height: "6' 0\"",
          weight: 220,
          "birth-place": "St. Paul, MN, USA",
          shoots: "RIght",
          birthday: "1988-04-16",
          "games-played": "835",
          goals: "198",
          assists: "321",
          points: "519",
        },
        {
          "player-name": "Casey Mittelstadt",
          "player-img": "Jack_Eichel_Buffalo_Sabres.png",
          "team-number": "37",
          position: "Center",
          height: "6'1\"",
          weight: "196",
          "birth-place": "Eden Prairie, MN, USA",
          shoots: "Left",
          birthday: "1998-11-22",
          "games-played": "155",
          goals: "27",
          assists: "34",
          points: "61",
        },
        {
          "player-name": "Dylan Cozens",
          "player-img": "Carter_Hutton_Buffalo_Sabres.png",
          "team-number": "24",
          position: "Center",
          height: "6'3\"",
          weight: "188",
          "birth-place": "Whitehorse, YT, CAN",
          shoots: "Right",
          birthday: "2001-02-09",
          "games-played": "41",
          goals: "4",
          assists: "9",
          points: "13",
        },
      ],
    },
    senators: {
      "franchise-name": "Senators",
      "franchise-location": "Ottawa",
      country: "CA",
      locale: "fr-CA",
      players: [
        {
          "player-name": "Drake Batherson",
          "player-img": "Erik_Gudbranson_Ottawa_Senators.png",
          "team-number": "44",
          position: "Defencemen",
          height: "6'5\"",
          weight: "217 lb",
          "birth-place": "Ottawa, ON, CAN",
          shoots: "Right",
          birthday: "1992-01-07",
          "games-played": "518",
          goals: "20",
          assists: "53",
          points: "73",
        },
        {
          "player-name": "Brady Tkachuk",
          "player-img": "BradytkachukEDIT.png",
          "team-number": "7",
          position: "Left Wing",
          height: "6'4\"",
          weight: "211 Ib",
          "birth-place": "Scottsdale, AZ, USA",
          shoots: "Left",
          birthday: "1999-09-16",
          "games-played": "198",
          goals: "60",
          assists: "65",
          points: "125",
        },
        {
          "player-name": "Colin White",
          "player-img": "White.png",
          "team-number": "36",
          position: "Centerman",
          height: "6'1\"",
          weight: "197 Ib",
          "birth-place": "Boston, MA, USA",
          shoots: "Right",
          birthday: "1997-01-30",
          "games-played": "200",
          goals: "33",
          assists: "55",
          points: "88",
        },
        {
          "player-name": "Matt Murray",
          "player-img": "Senators_Murray_Matt.png",
          "team-number": "30",
          position: "Goaltender",
          height: "6'4\"",
          weight: "178 Ib",
          "birth-place": "Thunder Bay, ON, CAN",
          shoots: "Left",
          birthday: "1994-05-25",
          "games-played": "226",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Tim Stützle",
          "player-img": "Christian_Wolanin_Ottawa_Senators.png",
          "team-number": "24",
          position: "Defencemen",
          height: "6'2\"",
          weight: "185 lb",
          "birth-place": "Quebec City, QB, CAN",
          shoots: "Left",
          birthday: "1995-03-17",
          "games-played": "43",
          goals: "5",
          assists: "10",
          points: "15",
        },
        {
          "player-name": "Thomas Chabot",
          "player-img": "ChabotHeadshotEDIT.png",
          "team-number": "72",
          position: "Defencemen",
          height: "6'2\"",
          weight: "190 Ib",
          "birth-place": "Sainte-Marie, QC, CAN",
          shoots: "Left",
          birthday: "1997-01-30",
          "games-played": "254",
          goals: "35",
          assists: "115",
          points: "150",
        },
      ],
    },
    sharks: {
      "franchise-name": "Sharks",
      "franchise-location": "San Jose",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Logan Couture",
          "player-img": "Sharks_Couture_Headshot.png",
          "team-number": 39,
          position: "Center",
          height: "6' 1\"",
          weight: 200,
          "birth-place": "Guelph, ON, Canada",
          shoots: "Left",
          birthday: "1989-03-28",
          "games-played": "768",
          goals: "273",
          assists: "304",
          points: "577",
        },
        {
          "player-name": "Evander Kane",
          "player-img": "Kane.png",
          "team-number": 9,
          position: "Goalie",
          height: "6' 2 \"",
          weight: 210,
          "birth-place": "Vancouver, BC, Canada",
          shoots: "Left",
          birthday: "1991-08-02",
          "games-played": 713,
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Tomas Hertl",
          "player-img": "Sharks_Hertl_Headshot.png",
          "team-number": 48,
          position: "Center",
          height: "6' 2\"",
          weight: 210,
          "birth-place": "Praha, Czech Republic",
          shoots: "Left",
          birthday: "1993-11-12",
          "games-played": "503",
          goals: "151",
          assists: "172",
          points: "323",
        },
        {
          "player-name": "Erik Karlsson",
          "player-img": "Karlsson.png",
          "team-number": 65,
          position: "Defense",
          height: "6' 0 \"",
          weight: 190,
          "birth-place": "Landsbro, Sweden",
          shoots: "Right",
          birthday: "1990-05-31",
          "games-played": 736,
          goals: "135",
          assists: "468",
          points: "603",
        },
        {
          "player-name": "Brent Burns",
          "player-img": "Sharks_Burns_Headshot.png",
          "team-number": 88,
          position: "Defenseman",
          height: "6' 5\"",
          weight: 230,
          "birth-place": "Barrie, ON, Canada",
          shoots: "Right",
          birthday: "1985-03-09",
          "games-played": "1169",
          goals: "217",
          assists: "506",
          points: "723",
        },
        {
          "player-name": "Timo Meier",
          "player-img": "Martin_Jones_San_Jose_Sharks.png",
          "team-number": "28",
          position: "Right Wing",
          height: "6'0\"",
          weight: "210",
          "birth-place": "Herisau, CHE",
          shoots: "Left",
          birthday: "1996-10-08",
          "games-played": "317",
          goals: "88",
          assists: "100",
          points: "188",
        },
      ],
    },
    stars: {
      "franchise-name": "Stars",
      "franchise-location": "Dallas",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Jamie Benn",
          "player-img": "Stars_Benn_14.png",
          "team-number": 14,
          position: "Left Wing",
          height: "6' 2\"",
          weight: 210,
          "birth-place": "Victoria, BC, Canada",
          shoots: "Left",
          birthday: "1989-07-18",
          "games-played": "866",
          goals: "311",
          assists: "412",
          points: "723",
        },
        {
          "player-name": "Alexander Radulov",
          "player-img": "AlexanderRadulov.png",
          "team-number": 47,
          position: "Right Wing",
          height: "6' 1 \"",
          weight: 201,
          "birth-place": "Nizhny Tagil, Russia",
          shoots: "Left",
          birthday: "1986-04-05",
          "games-played": "453",
          goals: "140",
          assists: "206",
          points: "346",
        },
        {
          "player-name": "Tyler Seguin",
          "player-img": "Stars_Seguin_91.png",
          "team-number": 91,
          position: "Center",
          height: "6' 1\"",
          weight: 200,
          "birth-place": "Brampton, ON, Canada",
          shoots: "Right",
          birthday: "1992-01-31",
          "games-played": "744",
          goals: "281",
          assists: "356",
          points: "637",
        },
        {
          "player-name": "John Klingberg",
          "player-img": "Stars_Klingberg_3.png",
          "team-number": 3,
          position: "Defenseman",
          height: "6' 2\"",
          weight: 180,
          "birth-place": "Gothenburg, Sweden",
          shoots: "Right",
          birthday: "1992-08-14",
          "games-played": 425,
          goals: "58",
          assists: "233",
          points: "291",
        },
        {
          "player-name": "Miro Heiskanen",
          "player-img": "Heiskanen.png",
          "team-number": 4,
          position: "Defense",
          height: "6' 1 \"",
          weight: 185,
          "birth-place": "Espoo, Finland",
          shoots: "Left",
          birthday: "1999-07-18",
          "games-played": "205",
          goals: "28",
          assists: "67",
          points: "95",
        },
        {
          "player-name": "Ben Bishop",
          "player-img": "Bishop.png",
          "team-number": 30,
          position: "Goalie",
          height: "6' 7\"",
          weight: 216,
          "birth-place": "Denver, Colorado",
          shoots: "Left",
          birthday: "1986-11-21",
          "games-played": "413",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
      ],
    },
    wild: {
      "franchise-name": "Wild",
      "franchise-location": "Minnesota",
      country: "US",
      locale: "en-US",
      players: [
        {
          "player-name": "Matt Dumba",
          "player-img": "Dumba.png",
          "team-number": 26,
          position: "Defenseman",
          height: "6' 0\"",
          weight: 189,
          "birth-place": "Regina, SASK, Canada",
          shoots: "Right",
          birthday: "1994-07-25",
          "games-played": "462",
          goals: "68",
          assists: "127",
          points: "195",
        },
        {
          "player-name": "Kevin Fiala",
          "player-img": "Kevin_Fiala.png",
          "team-number": 22,
          position: "Left Wing",
          height: "5' 10 \"",
          weight: 193,
          "birth-place": "St. Gallen, CHE",
          shoots: "Left",
          birthday: "1996-07-22",
          "games-played": "337",
          goals: "91",
          assists: "107",
          points: "198",
        },
        {
          "player-name": "Ryan Suter",
          "player-img": "Wild_Suter_20.png",
          "team-number": 20,
          position: "Defenseman",
          height: "6' 1\"",
          weight: 200,
          "birth-place": "Madison, WI, United States",
          shoots: "Left",
          birthday: "1985-01-21",
          "games-played": 1142,
          goals: "90",
          assists: "498",
          points: "588",
        },
        {
          "player-name": "Zach Parise",
          "player-img": "Wild_Parise_11.png",
          "team-number": 11,
          position: "Left Wing",
          height: "5' 11\"",
          weight: 197,
          "birth-place": "Minneapolis, MN, United States",
          shoots: "Left",
          birthday: "1984-07-28",
          "games-played": 1015,
          goals: "386",
          assists: "406",
          points: "792",
        },
        {
          "player-name": "Cam Talbot",
          "player-img": "Wild_Talbot_Cam.png",
          "team-number": 33,
          position: "Goalie",
          height: "6' 4\"",
          weight: 196,
          "birth-place": "Caledonia, ON, Canada",
          shoots: "Left",
          birthday: "1987-07-05",
          "games-played": "347",
          goals: "N/A",
          assists: "N/A",
          points: "N/A",
        },
        {
          "player-name": "Jared Spurgeon",
          "player-img": "Wild_Spurgeon_Jared.png",
          "team-number": 46,
          position: "Defenseman",
          height: "5' 9\"",
          weight: 167,
          "birth-place": "Edmonton, AB, Canada",
          shoots: "Right",
          birthday: "1989-11-29",
          "games-played": "707",
          goals: "89",
          assists: "216",
          points: "305",
        },
      ],
    },
  },
};
